import type { DailyAnalysisInput, DailyAnalysisTeam } from '@/types/daily-analysis';

/** SEO 场次录入格式（date + kickoff 自动转为 kickoffAt / kickoffTimeDisplay） */
interface SeoAnalysisMatchSeed {
  slug: string;
  homeTeam: DailyAnalysisTeam;
  awayTeam: DailyAnalysisTeam;
  league: { slug: string; nameZh: string };
  prediction: string;
  confidence?: 'low' | 'medium' | 'high';
  /** 开球显示时间，如 03:00 */
  kickoff?: string;
  /** 比赛日期 YYYY-MM-DD（写入 slug 与 kickoffAt） */
  date: string;
  isHot: boolean;
  isFocus: boolean;
  /** @deprecated 第一批兼容，请用 kickoff */
  time?: string;
}

function seoKickoffUtcIso(date: string, kickoff: string): string {
  const [hh, mm = '00'] = kickoff.split(':');
  const h = parseInt(hh, 10);
  if (h >= 8) return `${date}T${hh.padStart(2, '0')}:${mm}:00.000Z`;
  return `${date}T19:00:00.000Z`;
}

function seoBatchToInput(seed: SeoAnalysisMatchSeed): DailyAnalysisInput {
  const kickoffDisplay = seed.kickoff ?? seed.time ?? '03:00';
  const confidence =
    seed.confidence ?? (seed.isFocus ? 'high' : seed.isHot ? 'medium' : 'low');

  return {
    slug: seed.slug,
    home: seed.homeTeam,
    away: seed.awayTeam,
    league: seed.league,
    kickoffAt: seoKickoffUtcIso(seed.date, kickoffDisplay),
    kickoffTimeDisplay: kickoffDisplay,
    direction: seed.prediction,
    options: {
      isHot: seed.isHot,
      isFocus: seed.isFocus,
      confidence,
      showOnHomepage: seed.isHot || seed.isFocus,
      featuredInLatest: seed.isFocus,
      publishedAt: `${seed.date}T08:00:00.000Z`,
    },
  };
}

// =============================================================================
//  批量分析页 · 唯一数据源（只改 ANALYSIS_MATCHES）
// =============================================================================
//
//  新增一条比赛 → 自动生成：
//  · /analysis/{slug}  SEO 页（标题 / description / JSON-LD）
//  · sitemap.xml
//  · 首页「今日重点赛事」卡片（options.showOnHomepage 默认 true）
//  · 首页「最新赛前分析」（options.featuredInLatest 或 isHot / isFocus）
//
//  slug 格式：{主队slug}-vs-{客队slug}-YYYY-MM-DD
//
//  ┌────────┬──────────────────────────────────────────────────────────────┐
//  │ 1 主队 │ home                                                           │
//  │ 2 客队 │ away                                                           │
//  │ 3 联赛 │ league                                                         │
//  │ 4 时间 │ kickoffAt + kickoffTimeDisplay                                 │
//  │ 5 分析 │ content（可省略，模板自动生成）                                  │
//  │ 6 推荐 │ direction                                                      │
//  └────────┴──────────────────────────────────────────────────────────────┘
//
//  更多场次模板见 mock-analyses-batch.ts（自动合并进系统，无需重复填写）
//  复制 ANALYSIS_MATCH_TEMPLATE 追加到本数组末尾。
// =============================================================================

export const ANALYSIS_MATCH_TEMPLATE: DailyAnalysisInput = {
  slug: 'home-slug-vs-away-slug-2026-06-01',
  home: { slug: 'home-slug', nameZh: '主队中文名' },
  away: { slug: 'away-slug', nameZh: '客队中文名' },
  league: { slug: 'epl', nameZh: '英超' },
  kickoffAt: '2026-06-01T19:00:00.000Z',
  kickoffTimeDisplay: '03:00',
  content: {
    homeForm: '主队近况…',
    awayForm: '客队近况…',
    attack: '进攻面…',
    defense: '防守面…',
    motivation: '战意…',
    pace: '节奏…',
  },
  direction: '大 2.5',
  options: {
    confidence: 'high',
    isHot: true,
    showOnHomepage: true,
    homepageOrder: 10,
    featuredInLatest: true,
    venueZh: '球场名',
    round: '第38轮',
  },
};

// =============================================================================
//  第一批 SEO 分析页 ×20（英超 / 西甲 / 德甲 / 意甲 / 欧冠 / 世界杯）
// =============================================================================
const SEO_BATCH_1: SeoAnalysisMatchSeed[] = [
  // —— 英超 ×4 ——
  {
    slug: 'chelsea-vs-tottenham-2026-06-07',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-07',
    time: '03:00',
    homeTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'liverpool-vs-arsenal-2026-06-08',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-08',
    time: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-chelsea-2026-06-09',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-09',
    time: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '曼城 -0.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'man-united-vs-tottenham-2026-06-10',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-10',
    time: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  // —— 西甲 ×3 ——
  {
    slug: 'real-madrid-vs-atletico-2026-06-11',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-11',
    time: '04:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    prediction: '皇马 0',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'barcelona-vs-sevilla-2026-06-12',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-12',
    time: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    prediction: '巴萨 -1',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'villarreal-vs-real-madrid-2026-06-13',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-13',
    time: '04:00',
    homeTeam: { slug: 'villarreal', nameZh: '比利亚雷亚尔', abbr: 'VIL' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    isHot: false,
    isFocus: false,
  },
  // —— 德甲 ×3 ——
  {
    slug: 'bayern-vs-leverkusen-2026-06-14',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-14',
    time: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    prediction: '拜仁 -0.75',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'dortmund-vs-bayern-2026-06-15',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-15',
    time: '02:30',
    homeTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'rb-leipzig-vs-dortmund-2026-06-16',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-16',
    time: '02:30',
    homeTeam: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '大 2.5',
    isHot: false,
    isFocus: false,
  },
  // —— 意甲 ×3 ——
  {
    slug: 'inter-vs-ac-milan-2026-06-17',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-17',
    time: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'juventus-vs-inter-2026-06-18',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-18',
    time: '03:00',
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '尤文 0',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'ac-milan-vs-juventus-2026-06-19',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-19',
    time: '03:00',
    homeTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    awayTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  // —— 欧冠 ×4 ——
  {
    slug: 'real-madrid-vs-psg-2026-06-20',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-20',
    time: '03:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-bayern-2026-06-21',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-21',
    time: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'liverpool-vs-barcelona-2026-06-22',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-22',
    time: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'arsenal-vs-inter-2026-06-23',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-23',
    time: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '阿森纳 -0.25',
    isHot: true,
    isFocus: false,
  },
  // —— 世界杯 ×3 ——
  {
    slug: 'brazil-vs-argentina-2026-06-24',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-24',
    time: '09:00',
    homeTeam: { slug: 'brazil', nameZh: '巴西', abbr: 'BRA' },
    awayTeam: { slug: 'argentina', nameZh: '阿根廷', abbr: 'ARG' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'france-vs-germany-2026-06-25',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-25',
    time: '09:00',
    homeTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    awayTeam: { slug: 'germany', nameZh: '德国', abbr: 'GER' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'england-vs-spain-2026-06-26',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-26',
    time: '09:00',
    homeTeam: { slug: 'england', nameZh: '英格兰', abbr: 'ENG' },
    awayTeam: { slug: 'spain', nameZh: '西班牙', abbr: 'ESP' },
    prediction: '英格兰 0',
    isHot: true,
    isFocus: true,
  },
];

// =============================================================================
//  第二批 SEO 分析页 ×30（2026-06-27 起 · 含 confidence + kickoff）
// =============================================================================
const SEO_BATCH_2: SeoAnalysisMatchSeed[] = [
  // —— 英超 ×6 ——
  {
    slug: 'arsenal-vs-chelsea-2026-06-27',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-27',
    kickoff: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'liverpool-vs-man-city-2026-06-28',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-28',
    kickoff: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-united-vs-arsenal-2026-06-29',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-29',
    kickoff: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '阿森纳 -0.25',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'chelsea-vs-liverpool-2026-06-30',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-30',
    kickoff: '03:00',
    homeTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'tottenham-vs-man-city-2026-07-01',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-07-01',
    kickoff: '03:00',
    homeTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '曼城 -0.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'man-united-vs-chelsea-2026-07-02',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-07-02',
    kickoff: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: true,
  },
  // —— 西甲 ×5 ——
  {
    slug: 'barcelona-vs-atletico-2026-07-03',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-03',
    kickoff: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    prediction: '巴萨 -0.25',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'real-madrid-vs-barcelona-2026-07-04',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-04',
    kickoff: '04:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'atletico-vs-real-madrid-2026-07-05',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-05',
    kickoff: '04:00',
    homeTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '皇马 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'barcelona-vs-real-madrid-2026-07-06',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-06',
    kickoff: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'sevilla-vs-barcelona-2026-07-07',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-07',
    kickoff: '04:00',
    homeTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '巴萨 -0.75',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 德甲 ×5 ——
  {
    slug: 'bayern-vs-dortmund-2026-07-08',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-08',
    kickoff: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '拜仁 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'dortmund-vs-bayern-2026-07-09',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-09',
    kickoff: '02:30',
    homeTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'leverkusen-vs-bayern-2026-07-10',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-10',
    kickoff: '02:30',
    homeTeam: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'bayern-vs-rb-leipzig-2026-07-11',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-11',
    kickoff: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    prediction: '拜仁 -1',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'stuttgart-vs-bayern-2026-07-12',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-12',
    kickoff: '02:30',
    homeTeam: { slug: 'stuttgart', nameZh: '斯图加特', abbr: 'STU' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '拜仁 -0.5',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 意甲 ×5 ——
  {
    slug: 'inter-vs-juventus-2026-07-13',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-13',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'ac-milan-vs-inter-2026-07-14',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-14',
    kickoff: '03:00',
    homeTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'juventus-vs-ac-milan-2026-07-15',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-15',
    kickoff: '03:00',
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '尤文 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'inter-vs-ac-milan-2026-07-16',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-16',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '国际米兰 -0.25',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'napoli-vs-inter-2026-07-17',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-17',
    kickoff: '03:00',
    homeTeam: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 欧冠 ×6 ——
  {
    slug: 'psg-vs-bayern-2026-07-18',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-18',
    kickoff: '03:00',
    homeTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'real-madrid-vs-liverpool-2026-07-19',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-19',
    kickoff: '03:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'barcelona-vs-man-city-2026-07-20',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-20',
    kickoff: '03:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'arsenal-vs-psg-2026-07-21',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-21',
    kickoff: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'inter-vs-real-madrid-2026-07-22',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-22',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '皇马 0',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-real-madrid-2026-07-23',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-23',
    kickoff: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  // —— 世界杯 ×3 ——
  {
    slug: 'portugal-vs-england-2026-07-24',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-24',
    kickoff: '09:00',
    homeTeam: { slug: 'portugal', nameZh: '葡萄牙', abbr: 'POR' },
    awayTeam: { slug: 'england', nameZh: '英格兰', abbr: 'ENG' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'netherlands-vs-france-2026-07-25',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-25',
    kickoff: '09:00',
    homeTeam: { slug: 'netherlands', nameZh: '荷兰', abbr: 'NED' },
    awayTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'argentina-vs-france-2026-07-26',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-26',
    kickoff: '09:00',
    homeTeam: { slug: 'argentina', nameZh: '阿根廷', abbr: 'ARG' },
    awayTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    prediction: '阿根廷 0',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
];

/**
 * 手动维护的分析场次（优先级高于批量模板同 slug）
 * 批量模板场次在 mock-analyses-batch.ts，由 analysis-registry 自动合并
 */
export const ANALYSIS_MATCHES: DailyAnalysisInput[] = [
  ...SEO_BATCH_1.map(seoBatchToInput),
  ...SEO_BATCH_2.map(seoBatchToInput),
  {
    slug: 'real-madrid-vs-barcelona-2026-05-27',
    home: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    away: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    league: { slug: 'la-liga', nameZh: '西甲' },
    kickoffAt: '2026-05-26T20:00:00.000Z',
    kickoffTimeDisplay: '04:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '皇马：主场 4 胜 1 和，近 5 场 14 入 4 失，伯纳乌压制力仍属西甲顶格；国家德比战意拉满，开场倾向高位逼抢。',
      awayForm:
        '巴萨：客场 3 胜 1 负，锋线转化率稳定但客场失球率偏高；近 5 场 11 入 7 失，需防反击被皇马速度惩罚。',
      attack:
        '皇马边路提速 + 禁区前沿远射威胁大；巴萨控球推进仍能制造 xG，双方破门路径清晰，不利于闷战格局。',
      defense:
        '皇马零封率一般，高位线身后有空档；巴萨客场中卫协防与定位球二点偏弱——德比往往互有进球。',
      motivation: '国家德比：市场热度高，大小球与亚盘临场波动会快于一般联赛场次。',
      pace: '预计上半场即有射门威胁，节奏偏快；早段进球会进一步推高总进球预期。',
    },
    options: {
      confidence: 'high',
      summary: '德比升盘配大球低水，对攻格局概率高于隐含概率',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 0,
      featuredInLatest: true,
      modelWinRate: 78,
      venueZh: '伯纳乌球场',
      round: '第37轮',
      pickType: 'over',
      lineOpen: '3.0',
      lineCurrent: '3.25',
      ouTrend: 'up',
      over25Prob: 78,
      publishedAt: '2026-05-27T06:00:00.000Z',
    },
  },
  {
    slug: 'bayern-vs-dortmund-2026-05-27',
    home: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    away: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    league: { slug: 'bundesliga', nameZh: '德甲' },
    kickoffAt: '2026-05-26T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    direction: '拜仁 -0.75',
    options: {
      confidence: 'high',
      summary: '半一低水配合主场统治力，主胜路径清晰',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 1,
      featuredInLatest: true,
      isFreePublic: true,
      isLiveUpdating: true,
      modelWinRate: 71,
      venueZh: '安联球场',
      round: '第33轮',
      pickType: 'home',
      lineOpen: '3.25',
      lineCurrent: '3.5',
      ouTrend: 'up',
      publishedAt: '2026-05-27T05:00:00.000Z',
    },
  },
  {
    slug: 'arsenal-vs-man-city-2026-05-26',
    home: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '阿森纳：主场 3 胜 1 负，控球压制稳定；近 5 场 11 入 7 失，酋长球场抢分战意足，对阵强队不保守。',
      awayForm:
        '曼城：客场火力维持高位，近 5 场 13 入 8 失；联赛争冠/抢二动机下客场仍会主动控场推进。',
      attack:
        '阿森纳两翼内切 + 萨卡一侧制造威胁；曼城中路渗透与肋部直塞效率高，双方均有稳定进球路径。',
      defense:
        '阿森纳高位线身后偶有被打穿；曼城客场失球不算少，强强对话更支撑大球而非单边零封。',
      motivation: '英超榜首大战：临场资金或同步推高热门盘与大球方向。',
      pace: '开场 15–25 分钟节奏偏快，不宜预期闷战；下半场若比分紧咬，对攻频率仍会维持。',
    },
    options: {
      confidence: 'high',
      summary: '升盘配合大球低水，对攻格局概率高于隐含概率',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 2,
      featuredInLatest: true,
      isLiveUpdating: true,
      modelWinRate: 75,
      venueZh: '酋长球场',
      round: '第38轮',
      pickType: 'over',
      lineOpen: '2.75',
      lineCurrent: '3.0',
      ouTrend: 'up',
      over25Prob: 75,
      publishedAt: '2026-05-26T06:00:00.000Z',
    },
  },
  {
    slug: 'man-united-vs-liverpool-2026-05-25',
    home: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    away: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '曼联：主场 3 胜 1 和走势，终结效率回升，但高位线身后空档仍易被利用；近 5 场 12 入 6 失，联赛第 6，老特拉福德抢分战意足。',
      awayForm:
        '利物浦：客场 4 胜 1 负，火力英超顶格；近 5 场 14 入 5 失，联赛第 2，争冠/抢二动机强，客场不会保守。',
      attack:
        '曼联近 5 场 12 球，远射与定位球占比升；利物浦近 5 场 14 球，两翼内切 + 中场前插形成稳定 xG，双方均有稳定破门路径。',
      defense:
        '曼联仅 2 场零封，肋部与反击连场被打穿；利物浦客场近 4 场场场有失球，中卫协防与二点保护是短板——「能攻难守」支撑大球逻辑。',
      motivation: '第 38 轮双红会，双方均需抢分；本场为今日重心，临场资金或推高热门盘与大球方向。',
      pace: '预计开场 15–20 分钟进入对攻，上半场即有射门威胁，不宜预期闷战；若早段进球，节奏将进一步加快。',
    },
    options: {
      confidence: 'high',
      picks: ['👉 方向：大 2.5', '👉 方向：利物浦 -0.5'],
      summary:
        '双红会节奏快、交锋大球率高，配合大小升 3 球大球低水，首选大2.5；比分参考 1-2、2-2。完整临场方向（水位确认、阵容与走地）开赛前会在 TG 更新。',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 3,
      isFreePublic: true,
      isLiveUpdating: true,
      modelWinRate: 72,
      venueZh: '老特拉福德',
      round: '第38轮',
      pickType: 'over',
      lineOpen: '2.75',
      lineCurrent: '3.0',
      ouTrend: 'up',
      over25Prob: 72,
      publishedAt: '2026-05-25T06:00:00.000Z',
    },
  },
  {
    slug: 'crystal-palace-vs-arsenal-2026-05-25',
    home: { slug: 'crystal-palace', nameZh: '水晶宮', abbr: 'CRY' },
    away: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T15:00:00.000Z',
    kickoffTimeDisplay: '23:00',
    direction: '客胜',
    options: {
      confidence: 'medium',
      summary: '战意与实力差支撑客队，浅盘小胜格局',
      isHot: true,
      showOnHomepage: true,
      homepageOrder: 4,
      featuredInLatest: false,
      isLiveUpdating: true,
      modelWinRate: 58,
      venueZh: 'Selhurst Park',
      round: '第38轮',
      pickType: 'away',
      ouTrend: 'stable',
      lineOpen: '2.5',
      lineCurrent: '2.5',
      publishedAt: '2026-05-24T10:00:00.000Z',
    },
  },
];

/** SEO 批次原始数据（供查阅 / 导出） */
export { SEO_BATCH_1, SEO_BATCH_2 };
