import type { PreMatchBrief } from '@/types/analysis';
import type {
  DailyAnalysisInput,
  DailyAnalysisOptions,
  DailyAnalysisTeam,
} from '@/types/daily-analysis';
import type { SeoArticle } from '@/types/seo-article';
import {
  SEO_HOT_BATCH_DATE,
  seoArticlesHot20260530,
} from '@/lib/seo-articles-hot-2026-05-30';

/** SEO 场次录入格式（date + kickoff 自动转为 kickoffAt / kickoffTimeDisplay） */
interface SeoAnalysisMatchSeed {
  slug: string;
  homeTeam: DailyAnalysisTeam;
  awayTeam: DailyAnalysisTeam;
  league: { slug: string; nameZh: string };
  prediction: string;
  confidence?: 'low' | 'medium' | 'high';
  /** 开球显示时间，如 03:00 */
  kickoff?: string;
  /** 比赛日期 YYYY-MM-DD（写入 slug 与 kickoffAt） */
  date: string;
  isHot: boolean;
  isFocus: boolean;
  /** @deprecated 第一批兼容，请用 kickoff */
  time?: string;
  /** ⑤ 赛前分析正文（stats 由 buildAnalysisPage 模板自动生成） */
  content?: PreMatchBrief;
  summary?: string;
  picks?: string[];
  modelWinRate?: number;
  lineOpen?: string;
  lineCurrent?: string;
  ouTrend?: DailyAnalysisOptions['ouTrend'];
  over25Prob?: number;
  pickType?: DailyAnalysisOptions['pickType'];
  venueZh?: string;
  round?: string;
  homepageOrder?: number;
}

function seoKickoffUtcIso(date: string, kickoff: string): string {
  const [hh, mm = '00'] = kickoff.split(':');
  const h = parseInt(hh, 10);
  if (h >= 8) return `${date}T${hh.padStart(2, '0')}:${mm}:00.000Z`;
  return `${date}T19:00:00.000Z`;
}

function seoBatchToInput(seed: SeoAnalysisMatchSeed): DailyAnalysisInput {
  const kickoffDisplay = seed.kickoff ?? seed.time ?? '03:00';
  const confidence =
    seed.confidence ?? (seed.isFocus ? 'high' : seed.isHot ? 'medium' : 'low');

  return {
    slug: seed.slug,
    home: seed.homeTeam,
    away: seed.awayTeam,
    league: seed.league,
    kickoffAt: seoKickoffUtcIso(seed.date, kickoffDisplay),
    kickoffTimeDisplay: kickoffDisplay,
    direction: seed.prediction,
    content: seed.content,
    options: {
      isHot: seed.isHot,
      isFocus: seed.isFocus,
      confidence,
      showOnHomepage: seed.isHot || seed.isFocus,
      featuredInLatest: seed.isFocus,
      publishedAt: `${seed.date}T08:00:00.000Z`,
      summary: seed.summary,
      picks: seed.picks,
      modelWinRate: seed.modelWinRate,
      lineOpen: seed.lineOpen,
      lineCurrent: seed.lineCurrent,
      ouTrend: seed.ouTrend,
      over25Prob: seed.over25Prob,
      pickType: seed.pickType,
      venueZh: seed.venueZh,
      round: seed.round,
      homepageOrder: seed.homepageOrder,
    },
  };
}

/** 每日 SEO 快速录入（slug = {home}-vs-{away}-{date}） */
function seoDailySeed(
  date: string,
  home: DailyAnalysisTeam,
  away: DailyAnalysisTeam,
  league: { slug: string; nameZh: string },
  prediction: string,
  content: PreMatchBrief,
  extra: Partial<SeoAnalysisMatchSeed> = {}
): SeoAnalysisMatchSeed {
  return {
    slug: extra.slug ?? `${home.slug}-vs-${away.slug}-${date}`,
    date,
    kickoff: extra.kickoff ?? '03:00',
    league,
    homeTeam: home,
    awayTeam: away,
    prediction,
    confidence: extra.confidence ?? 'medium',
    isHot: extra.isHot ?? true,
    isFocus: extra.isFocus ?? false,
    content,
    ...extra,
  };
}

// =============================================================================
//  批量分析页 · 唯一数据源（只改 ANALYSIS_MATCHES）
// =============================================================================
//
//  新增一条比赛 → 自动生成：
//  · /analysis/{slug}  SEO 页（标题 / description / JSON-LD）
//  · sitemap.xml
//  · 首页「今日重点赛事」卡片（options.showOnHomepage 默认 true）
//  · 首页「最新赛前分析」（options.featuredInLatest 或 isHot / isFocus）
//
//  slug 格式：{主队slug}-vs-{客队slug}-YYYY-MM-DD
//
//  ┌────────┬──────────────────────────────────────────────────────────────┐
//  │ 1 主队 │ home                                                           │
//  │ 2 客队 │ away                                                           │
//  │ 3 联赛 │ league                                                         │
//  │ 4 时间 │ kickoffAt + kickoffTimeDisplay                                 │
//  │ 5 分析 │ content（可省略，模板自动生成）                                  │
//  │ 6 推荐 │ direction                                                      │
//  └────────┴──────────────────────────────────────────────────────────────┘
//
//  更多场次模板见 mock-analyses-batch.ts（自动合并进系统，无需重复填写）
//  复制 ANALYSIS_MATCH_TEMPLATE 追加到本数组末尾。
// =============================================================================

export const ANALYSIS_MATCH_TEMPLATE: DailyAnalysisInput = {
  slug: 'home-slug-vs-away-slug-2026-06-01',
  home: { slug: 'home-slug', nameZh: '主队中文名' },
  away: { slug: 'away-slug', nameZh: '客队中文名' },
  league: { slug: 'epl', nameZh: '英超' },
  kickoffAt: '2026-06-01T19:00:00.000Z',
  kickoffTimeDisplay: '03:00',
  content: {
    homeForm: '主队近况…',
    awayForm: '客队近况…',
    attack: '进攻面…',
    defense: '防守面…',
    motivation: '战意…',
    pace: '节奏…',
  },
  direction: '大 2.5',
  options: {
    confidence: 'high',
    isHot: true,
    showOnHomepage: true,
    homepageOrder: 10,
    featuredInLatest: true,
    venueZh: '球场名',
    round: '第38轮',
  },
};

// =============================================================================
//  第一批 SEO 分析页 ×20（英超 / 西甲 / 德甲 / 意甲 / 欧冠 / 世界杯）
// =============================================================================
const SEO_BATCH_1: SeoAnalysisMatchSeed[] = [
  // —— 英超 ×4 ——
  {
    slug: 'chelsea-vs-tottenham-2026-06-07',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-07',
    time: '03:00',
    homeTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'liverpool-vs-arsenal-2026-06-08',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-08',
    time: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-chelsea-2026-06-09',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-09',
    time: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '曼城 -0.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'man-united-vs-tottenham-2026-06-10',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-10',
    time: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  // —— 西甲 ×3 ——
  {
    slug: 'real-madrid-vs-atletico-2026-06-11',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-11',
    time: '04:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    prediction: '皇马 0',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'barcelona-vs-sevilla-2026-06-12',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-12',
    time: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    prediction: '巴萨 -1',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'villarreal-vs-real-madrid-2026-06-13',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-06-13',
    time: '04:00',
    homeTeam: { slug: 'villarreal', nameZh: '比利亚雷亚尔', abbr: 'VIL' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    isHot: false,
    isFocus: false,
  },
  // —— 德甲 ×3 ——
  {
    slug: 'bayern-vs-leverkusen-2026-06-14',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-14',
    time: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    prediction: '拜仁 -0.75',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'dortmund-vs-bayern-2026-06-15',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-15',
    time: '02:30',
    homeTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'rb-leipzig-vs-dortmund-2026-06-16',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-06-16',
    time: '02:30',
    homeTeam: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '大 2.5',
    isHot: false,
    isFocus: false,
  },
  // —— 意甲 ×3 ——
  {
    slug: 'inter-vs-ac-milan-2026-06-17',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-17',
    time: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'juventus-vs-inter-2026-06-18',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-18',
    time: '03:00',
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '尤文 0',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'ac-milan-vs-juventus-2026-06-19',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-06-19',
    time: '03:00',
    homeTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    awayTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  // —— 欧冠 ×4 ——
  {
    slug: 'real-madrid-vs-psg-2026-06-20',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-20',
    time: '03:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-bayern-2026-06-21',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-21',
    time: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'liverpool-vs-barcelona-2026-06-22',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-22',
    time: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'arsenal-vs-inter-2026-06-23',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-06-23',
    time: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '阿森纳 -0.25',
    isHot: true,
    isFocus: false,
  },
  // —— 世界杯 ×3 ——
  {
    slug: 'brazil-vs-argentina-2026-06-24',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-24',
    time: '09:00',
    homeTeam: { slug: 'brazil', nameZh: '巴西', abbr: 'BRA' },
    awayTeam: { slug: 'argentina', nameZh: '阿根廷', abbr: 'ARG' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'france-vs-germany-2026-06-25',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-25',
    time: '09:00',
    homeTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    awayTeam: { slug: 'germany', nameZh: '德国', abbr: 'GER' },
    prediction: '大 2.5',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'england-vs-spain-2026-06-26',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-06-26',
    time: '09:00',
    homeTeam: { slug: 'england', nameZh: '英格兰', abbr: 'ENG' },
    awayTeam: { slug: 'spain', nameZh: '西班牙', abbr: 'ESP' },
    prediction: '英格兰 0',
    isHot: true,
    isFocus: true,
  },
];

// =============================================================================
//  第二批 SEO 分析页 ×30（2026-06-27 起 · 含 confidence + kickoff）
// =============================================================================
const SEO_BATCH_2: SeoAnalysisMatchSeed[] = [
  // —— 英超 ×6 ——
  {
    slug: 'arsenal-vs-chelsea-2026-06-27',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-27',
    kickoff: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'liverpool-vs-man-city-2026-06-28',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-28',
    kickoff: '03:00',
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-united-vs-arsenal-2026-06-29',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-29',
    kickoff: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '阿森纳 -0.25',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'chelsea-vs-liverpool-2026-06-30',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-06-30',
    kickoff: '03:00',
    homeTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'tottenham-vs-man-city-2026-07-01',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-07-01',
    kickoff: '03:00',
    homeTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '曼城 -0.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'man-united-vs-chelsea-2026-07-02',
    league: { slug: 'epl', nameZh: '英超' },
    date: '2026-07-02',
    kickoff: '03:00',
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: true,
  },
  // —— 西甲 ×5 ——
  {
    slug: 'barcelona-vs-atletico-2026-07-03',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-03',
    kickoff: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    prediction: '巴萨 -0.25',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'real-madrid-vs-barcelona-2026-07-04',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-04',
    kickoff: '04:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'atletico-vs-real-madrid-2026-07-05',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-05',
    kickoff: '04:00',
    homeTeam: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '皇马 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'barcelona-vs-real-madrid-2026-07-06',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-06',
    kickoff: '04:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'sevilla-vs-barcelona-2026-07-07',
    league: { slug: 'la-liga', nameZh: '西甲' },
    date: '2026-07-07',
    kickoff: '04:00',
    homeTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '巴萨 -0.75',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 德甲 ×5 ——
  {
    slug: 'bayern-vs-dortmund-2026-07-08',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-08',
    kickoff: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '拜仁 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'dortmund-vs-bayern-2026-07-09',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-09',
    kickoff: '02:30',
    homeTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'leverkusen-vs-bayern-2026-07-10',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-10',
    kickoff: '02:30',
    homeTeam: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'bayern-vs-rb-leipzig-2026-07-11',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-11',
    kickoff: '02:30',
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    prediction: '拜仁 -1',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'stuttgart-vs-bayern-2026-07-12',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    date: '2026-07-12',
    kickoff: '02:30',
    homeTeam: { slug: 'stuttgart', nameZh: '斯图加特', abbr: 'STU' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '拜仁 -0.5',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 意甲 ×5 ——
  {
    slug: 'inter-vs-juventus-2026-07-13',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-13',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'ac-milan-vs-inter-2026-07-14',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-14',
    kickoff: '03:00',
    homeTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'juventus-vs-ac-milan-2026-07-15',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-15',
    kickoff: '03:00',
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '尤文 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'inter-vs-ac-milan-2026-07-16',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-16',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '国际米兰 -0.25',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'napoli-vs-inter-2026-07-17',
    league: { slug: 'serie-a', nameZh: '意甲' },
    date: '2026-07-17',
    kickoff: '03:00',
    homeTeam: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    awayTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: false,
    isFocus: false,
  },
  // —— 欧冠 ×6 ——
  {
    slug: 'psg-vs-bayern-2026-07-18',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-18',
    kickoff: '03:00',
    homeTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    awayTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'real-madrid-vs-liverpool-2026-07-19',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-19',
    kickoff: '03:00',
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'barcelona-vs-man-city-2026-07-20',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-20',
    kickoff: '03:00',
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 3',
    confidence: 'high',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'arsenal-vs-psg-2026-07-21',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-21',
    kickoff: '03:00',
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'psg', nameZh: '巴黎', abbr: 'PSG' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'inter-vs-real-madrid-2026-07-22',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-22',
    kickoff: '03:00',
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '皇马 0',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  {
    slug: 'man-city-vs-real-madrid-2026-07-23',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    date: '2026-07-23',
    kickoff: '03:00',
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
  // —— 世界杯 ×3 ——
  {
    slug: 'portugal-vs-england-2026-07-24',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-24',
    kickoff: '09:00',
    homeTeam: { slug: 'portugal', nameZh: '葡萄牙', abbr: 'POR' },
    awayTeam: { slug: 'england', nameZh: '英格兰', abbr: 'ENG' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'netherlands-vs-france-2026-07-25',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-25',
    kickoff: '09:00',
    homeTeam: { slug: 'netherlands', nameZh: '荷兰', abbr: 'NED' },
    awayTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
  },
  {
    slug: 'argentina-vs-france-2026-07-26',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    date: '2026-07-26',
    kickoff: '09:00',
    homeTeam: { slug: 'argentina', nameZh: '阿根廷', abbr: 'ARG' },
    awayTeam: { slug: 'france', nameZh: '法国', abbr: 'FRA' },
    prediction: '阿根廷 0',
    confidence: 'high',
    isHot: true,
    isFocus: true,
  },
];

// =============================================================================
//  每日 SEO 热门（改 SEO_DAILY_DATE + SEO_DAILY_TODAY 即可每日更新）
// =============================================================================
export const SEO_DAILY_DATE = SEO_HOT_BATCH_DATE;

/** 将 SEO 长文批次转为 analysis-matches 种子（与 seo-articles.ts 同步） */
function seoArticleToSeed(article: SeoArticle): SeoAnalysisMatchSeed {
  const o = article.options ?? {};
  return {
    slug: article.slug,
    date: SEO_DAILY_DATE,
    kickoff: article.match.kickoffTime,
    homeTeam: article.match.home,
    awayTeam: article.match.away,
    league: article.match.league,
    prediction: article.direction,
    content: article.analysis,
    confidence: o.confidence,
    isHot: o.isHot ?? true,
    isFocus: o.isFocus ?? false,
    modelWinRate: o.modelWinRate,
    lineOpen: o.lineOpen,
    lineCurrent: o.lineCurrent,
    ouTrend: o.ouTrend,
    over25Prob: o.over25Prob,
    pickType: o.pickType,
    venueZh: o.venueZh,
    round: o.round,
    homepageOrder: o.homepageOrder,
  };
}

const SEO_DAILY_2026_05_25: SeoAnalysisMatchSeed[] = [
  {
    slug: 'liverpool-vs-man-city-2026-05-25',
    date: '2026-05-25',
    kickoff: '20:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 10,
    venueZh: '安菲尔德',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 74,
    modelWinRate: 73,
    picks: ['👉 方向：大 2.5', '👉 方向：利物浦 0'],
    summary: '榜首对攻、大小升盘配低水，首选大2.5；比分参考 2-2、2-1。',
    content: {
      homeForm: '利物浦：主场 4 胜 1 负，前场压迫与转换效率英超顶格；近 5 场 15 入 6 失，安菲尔德抢分战意足。',
      awayForm: '曼城：客场火力维持，近 5 场 14 入 7 失；争冠动机下不会保守，肋部渗透威胁大。',
      attack: '利物浦高位逼抢 + 两翼提速；曼城中路渗透与定位球占比高，双方均有稳定 xG 路径。',
      defense: '利物浦仅 2 场零封，高位线身后空档易被利用；曼城客场连场有失球，强强对话支撑大球。',
      motivation: '英超榜首直接对话，临场资金或推高热门盘与大球方向。',
      pace: '预计开场 15 分钟进入对攻，上半场即有射门威胁，不宜预期闷战。',
    },
  },
  {
    slug: 'man-united-vs-arsenal-2026-05-25',
    date: '2026-05-25',
    kickoff: '23:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 11,
    venueZh: '老特拉福德',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 68,
    modelWinRate: 70,
    summary: '曼联主场敢攻、阿森纳客场不保守，大小升盘逻辑成立。',
    content: {
      homeForm: '曼联：主场 3 胜 1 和，终结效率回升；近 5 场 11 入 8 失，老特拉福德需抢分。',
      awayForm: '阿森纳：客场 3 胜 2 负，控球压制稳定；近 5 场 12 入 6 失，对阵中游以上不收缩。',
      attack: '曼联远射与定位球占比升；阿森纳两翼内切 + 萨卡一侧制造威胁，双方破门路径清晰。',
      defense: '曼联肋部与反击连场被打穿；阿森纳高位线身后偶有漏洞——「能攻难守」支撑大球。',
      motivation: '争四/欧战席位关键战，双方均需抢分，战术上不会长时间闷守。',
      pace: '下半场若比分紧咬，对攻频率仍会维持；早段进球将进一步拉高节奏。',
    },
  },
  {
    slug: 'man-city-vs-liverpool-2026-05-25',
    date: '2026-05-25',
    kickoff: '03:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '曼城 -0.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 12,
    venueZh: '伊蒂哈德球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '曼城 -0.25',
    lineCurrent: '曼城 -0.5',
    ouTrend: 'stable',
    modelWinRate: 71,
    picks: ['👉 方向：曼城 -0.5', '👉 方向：大 2.5'],
    summary: '主场盘口升档、资金承接主队，浅盘小胜格局可期。',
    content: {
      homeForm: '曼城：主场 4 胜 1 负，控球与禁区压制力顶级；近 5 场 16 入 5 失，伊蒂哈德抢分稳定。',
      awayForm: '利物浦：客场 4 胜 1 负，火力维持；近 5 场 13 入 6 失，客场不会保守但防线速度是考验。',
      attack: '曼城中路渗透 + 肋部直塞效率高；利物浦转换与两翼内切形成稳定 xG，总进球仍可期。',
      defense: '曼城主场零封率尚可；利物浦客场近 4 场场场有失球，受让深盘下客队难稳守。',
      motivation: '争冠/抢二直接对话，曼城主场战意与历史盘口支持让球方。',
      pace: '曼城倾向控球消耗后提速；利物浦若早段失球会拉高节奏，亚盘升盘与赛果盘同向。',
    },
  },
  {
    slug: 'arsenal-vs-liverpool-2026-05-25',
    date: '2026-05-25',
    kickoff: '22:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '利物浦 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 13,
    venueZh: '酋长球场',
    round: '第38轮',
    pickType: 'away',
    lineOpen: '平手',
    lineCurrent: '利物浦 0',
    ouTrend: 'stable',
    modelWinRate: 62,
    summary: '客队近况与交锋占优，平手盘下跟利物浦方向。',
    content: {
      homeForm: '阿森纳：主场 3 胜 1 负，控球稳定；近 5 场 10 入 7 失，对阵强队偶有起伏。',
      awayForm: '利物浦：客场 4 胜 1 负，转换效率英超顶格；近 5 场 14 入 5 失，客场抢分动机强。',
      attack: '阿森纳两翼内切制造威胁；利物浦前场压迫 + 快速转换，客场 xG 维持高位。',
      defense: '阿森纳高位线身后空档需防；利物浦客场失球不多但中卫协防仍是短板。',
      motivation: '争冠/抢二关键战，利物浦客场战意与盘口资金同向客队。',
      pace: '预计上半场谨慎试探，下半场利物浦提速抢分概率更高。',
    },
  },
  {
    slug: 'man-united-vs-man-city-2026-05-25',
    date: '2026-05-25',
    kickoff: '01:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 14,
    venueZh: '老特拉福德',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 76,
    modelWinRate: 72,
    summary: '曼市德比大球率高，升盘降水示好总进球，首选大2.5。',
    content: {
      homeForm: '曼联：主场敢攻，近 5 场 12 入 9 失；德比战意足，老特拉福德不会长时间退守。',
      awayForm: '曼城：客场火力维持，近 5 场 15 入 6 失；德比客场仍以控球压制为主。',
      attack: '曼联定位球与远射占比升；曼城禁区压制 + 肋部渗透，双方破门路径稳定。',
      defense: '曼联防线松动连场有失球；曼城客场零封率一般——德比「能攻难守」逻辑成立。',
      motivation: '曼市德比 + 联赛排名压力，情绪与节奏均不利于闷战。',
      pace: '历史德比多早段进球，不宜预期低节奏；临场若维持 3.25 大球低水可跟。',
    },
  },
  {
    slug: 'real-madrid-vs-liverpool-2026-05-25',
    date: '2026-05-25',
    kickoff: '04:00',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 15,
    venueZh: '伯纳乌',
    round: '半决赛',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 77,
    modelWinRate: 74,
    picks: ['👉 方向：大 2.5', '👉 方向：皇马 0'],
    summary: '欧冠强强对话、大小升盘，伯纳乌主场与大球方向共振。',
    content: {
      homeForm: '皇马：主场欧冠稳定，近 5 场 13 入 5 失；淘汰赛主场战意与经验占优。',
      awayForm: '利物浦：客场火力英超顶格，近 5 场 14 入 6 失；欧冠客场不会保守。',
      attack: '皇马边路提速 + 禁区压制；利物浦转换与定位球威胁大，双方 xG 路径清晰。',
      defense: '皇马主场零封率尚可但高位线有风险；利物浦客场连场有失球，支撑大球大于单边零封。',
      motivation: '欧冠半决赛首回合/关键战，平局对双方均不理想，节奏偏快。',
      pace: '伯纳乌夜战惯有早段进球，大小 3 球盘下大球低水值得跟进。',
    },
  },
  {
    slug: 'bayern-vs-psg-2026-05-25',
    date: '2026-05-25',
    kickoff: '03:00',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'psg', nameZh: '巴黎圣日耳曼', abbr: 'PSG' },
    prediction: '拜仁 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 16,
    venueZh: '安联球场',
    round: '半决赛',
    pickType: 'home',
    lineOpen: '拜仁 -0.5',
    lineCurrent: '拜仁 -0.75',
    ouTrend: 'up',
    modelWinRate: 73,
    summary: '拜仁主场盘口升档，安联压制力支持让球方小胜。',
    content: {
      homeForm: '拜仁：主场 4 胜 1 负，禁区压制德甲顶级；近 5 场 17 入 6 失，欧冠主场抢分稳。',
      awayForm: '巴黎：客场起伏，近 5 场 11 入 9 失；欧冠客场防守转换速度是隐患。',
      attack: '拜仁高位逼抢 + 边路内切，场均进球维持 3+；巴黎依赖锋线个人能力，创造机会波动大。',
      defense: '拜仁协防尚可但定位球二点偶弱；巴黎客场中卫回追与肋部保护连场被打穿。',
      motivation: '欧冠半决赛，拜仁主场必须建立优势，战术上主动控场。',
      pace: '预计拜仁上半场高压，巴黎反击有威胁但难稳守深盘；亚盘升盘与主胜方向同向。',
    },
  },
  {
    slug: 'man-city-vs-real-madrid-2026-05-25',
    date: '2026-05-25',
    kickoff: '03:00',
    league: { slug: 'champions-league', nameZh: '欧冠' },
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 17,
    venueZh: '伊蒂哈德球场',
    round: '四分之一决赛',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 70,
    modelWinRate: 68,
    summary: '两队欧冠进攻火力足，大小由 2.5 升至 2.75，跟大球方向。',
    content: {
      homeForm: '曼城：主场欧冠控球压制，近 5 场 15 入 5 失；伊蒂哈德创造机会稳定。',
      awayForm: '皇马：客场欧冠经验足，近 5 场 12 入 7 失；淘汰赛客场仍会寻找反击空间。',
      attack: '曼城中路渗透效率高；皇马边路提速 + 转换犀利，总进球可期。',
      defense: '曼城高位线身后偶有被打穿；皇马客场失球不算少，强强对话支撑大球。',
      motivation: '欧冠淘汰赛，平局对主队不利，曼城主场倾向主动提速。',
      pace: '伊蒂哈德夜战节奏偏快，不宜预期 0-0 闷战；临场大球低水可跟。',
    },
  },
  {
    slug: 'brazil-vs-germany-2026-05-25',
    date: '2026-05-25',
    kickoff: '09:00',
    league: { slug: 'world-cup-2026', nameZh: '世界杯' },
    homeTeam: { slug: 'brazil', nameZh: '巴西', abbr: 'BRA' },
    awayTeam: { slug: 'germany', nameZh: '德国', abbr: 'GER' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 18,
    venueZh: 'MetLife Stadium',
    round: '小组赛',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 72,
    modelWinRate: 71,
    summary: '世界杯强强对话，大小升盘 + 大球低水，首选大2.5。',
    content: {
      homeForm: '巴西：小组赛开局 2 胜，前场创造力南美顶格；近 3 场 7 入 2 失，进攻节奏快。',
      awayForm: '德国：传控与高位压迫成熟，近 3 场 6 入 3 失；世界杯大赛经验充足。',
      attack: '巴西边路个人能力与中路插上；德国肋部渗透 + 定位球，双方均有稳定破门路径。',
      defense: '巴西高位线身后需防德国直塞；德国中卫协防在快节奏下偶有漏洞。',
      motivation: '世界杯小组出线关键战，平局对双方均不理想，战术上偏对攻。',
      pace: '大赛早段常谨慎，但两队实力差小、大小盘升档，总进球方向更值得跟进。',
    },
  },
  {
    slug: 'barcelona-vs-real-madrid-2026-05-25',
    date: '2026-05-25',
    kickoff: '04:15',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 19,
    venueZh: '诺坎普',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 78,
    modelWinRate: 75,
    picks: ['👉 方向：大 2.5', '👉 方向：巴萨 0'],
    summary: '国家德比大球率高，诺坎普夜战升盘降水，首选大2.5。',
    content: {
      homeForm: '巴萨：主场 4 胜 1 负，控球与肋部渗透稳定；近 5 场 13 入 6 失，诺坎普战意足。',
      awayForm: '皇马：客场 3 胜 2 负，转换与边路威胁大；近 5 场 14 入 7 失，德比不会保守。',
      attack: '巴萨中路渗透 + 两翼提速；皇马反击与定位球占比高，双方 xG 路径清晰。',
      defense: '巴萨高位线身后空档需防；皇马客场失球不算少——德比「能攻难守」支撑大球。',
      motivation: '西甲争冠/国家德比，情绪与节奏均不利于闷战，临场资金或推高大小盘。',
      pace: '历史国家德比多早段进球，大小 3 球盘下大球低水值得跟进。',
    },
  },
];

const SEO_DAILY_2026_05_26: SeoAnalysisMatchSeed[] = [
  {
    slug: 'man-city-vs-chelsea-2026-05-26',
    date: '2026-05-26',
    kickoff: '23:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '曼城 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 20,
    venueZh: '伊蒂哈德球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '曼城 -0.5',
    lineCurrent: '曼城 -0.75',
    ouTrend: 'stable',
    modelWinRate: 74,
    picks: ['👉 方向：曼城 -0.75', '👉 方向：大 2.5'],
    summary: '主场盘口升档、切尔西客场防守波动，浅盘跟曼城方向。',
    content: {
      homeForm: '曼城：主场 4 胜 1 负，控球与禁区压制力顶级；近 5 场 16 入 5 失，伊蒂哈德抢分稳定。',
      awayForm: '切尔西：客场 2 胜 2 负 1 和，进攻创造力尚可；近 5 场 9 入 11 失，客场防线连场有失球。',
      attack: '曼城中路渗透 + 肋部直塞效率高；切尔西依赖转换与定位球，面对高压时出球质量下降。',
      defense: '曼城主场零封率尚可；切尔西客场肋部与反击隐患大，深盘下难稳守全场。',
      motivation: '英超争冠/抢二关键战，曼城主场必须拿分，战术上主动控场压制。',
      pace: '临场建议：开赛前 30 分钟确认亚盘，若维持 -0.75 主队低水可跟；若退至 -0.5 且主队升水则减仓。大小球临场回落至 2.75 且大球升水则观望大球。',
    },
  },
  {
    slug: 'arsenal-vs-tottenham-2026-05-26',
    date: '2026-05-26',
    kickoff: '22:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 21,
    venueZh: '酋长球场',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 73,
    modelWinRate: 72,
    picks: ['👉 方向：大 2.5', '👉 方向：阿森纳 -0.5'],
    summary: '北伦敦德比大球率高，大小升盘配低水，首选大2.5。',
    content: {
      homeForm: '阿森纳：主场 3 胜 1 负，控球压制稳定；近 5 场 11 入 7 失，酋长球场战意足。',
      awayForm: '热刺：客场 3 胜 2 负，反击与边路威胁大；近 5 场 12 入 9 失，德比客场不会长时间退守。',
      attack: '阿森纳两翼内切 + 萨卡一侧制造威胁；热刺转换效率英超上游，双方均有稳定破门路径。',
      defense: '阿森纳高位线身后偶有被打穿；热刺客场失球不算少——德比「能攻难守」支撑大球。',
      motivation: '北伦敦德比 + 争四/欧战席位，情绪与节奏均不利于闷战。',
      pace: '临场建议：若大小维持 3 球且大球水位 ≤0.90 可跟大2.5；早段若有进球可保留走地大球选项。亚盘若阿森纳退至 -0.25 且升水，改以大小为主。',
    },
  },
  {
    slug: 'real-madrid-vs-barcelona-2026-05-26',
    date: '2026-05-26',
    kickoff: '04:00',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 22,
    venueZh: '伯纳乌',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 78,
    modelWinRate: 76,
    picks: ['👉 方向：大 2.5', '👉 方向：皇马 0'],
    summary: '国家德比大球率高，伯纳乌夜战升盘降水，首选大2.5。',
    content: {
      homeForm: '皇马：主场 4 胜 1 和，近 5 场 14 入 4 失，伯纳乌压制力仍属西甲顶格。',
      awayForm: '巴萨：客场 3 胜 2 负，控球与肋部渗透稳定；近 5 场 13 入 6 失，国家德比战意拉满。',
      attack: '皇马边路提速 + 禁区压制；巴萨中路渗透 + 两翼提速，双方 xG 路径清晰。',
      defense: '皇马主场零封率尚可但高位线有风险；巴萨客场失球不算少，德比更支撑大球。',
      motivation: '西甲争冠/国家德比，平局对双方均不理想，节奏偏快。',
      pace: '临场建议：伯纳乌夜战惯有早段进球，大小 3 球大球低水可跟；若临场退至 2.75 且大球升水则观望。完整水位与阵容变动开赛前 TG 更新。',
    },
  },
  {
    slug: 'inter-vs-ac-milan-2026-05-26',
    date: '2026-05-26',
    kickoff: '02:45',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '国米 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 23,
    venueZh: '梅阿查球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '平手',
    lineCurrent: '国米 0',
    ouTrend: 'stable',
    modelWinRate: 66,
    summary: '米兰德比，国米主场近况与盘口资金同向，平手跟主队。',
    content: {
      homeForm: '国米：主场 4 胜 1 负，攻防均衡；近 5 场 12 入 5 失，梅阿查抢分动机强。',
      awayForm: 'AC米兰：客场 2 胜 2 负 1 和，终结效率波动；近 5 场 8 入 9 失，德比客场防线是考验。',
      attack: '国米中路渗透 + 两翼内切稳定；米兰依赖反击与定位球，创造机会质量起伏大。',
      defense: '国米主场协防尚可；米兰客场肋部保护连场被打穿，受让平手盘下客队难稳守。',
      motivation: '米兰德比 + 欧冠/联赛排名压力，国米主场战意更足。',
      pace: '临场建议：平手盘下若国米水位持续走低可跟；若升为高水且大小降盘则观望。开赛前确认主力中卫是否缺阵再定仓位。',
    },
  },
  {
    slug: 'bayern-vs-dortmund-2026-05-26',
    date: '2026-05-26',
    kickoff: '02:30',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '拜仁 -0.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 24,
    venueZh: '安联球场',
    round: '第34轮',
    pickType: 'home',
    lineOpen: '拜仁 -0.25',
    lineCurrent: '拜仁 -0.5',
    ouTrend: 'up',
    modelWinRate: 73,
    picks: ['👉 方向：拜仁 -0.5', '👉 方向：大 2.5'],
    summary: '国家德比，拜仁主场盘口升档，安联压制力支持让球方。',
    content: {
      homeForm: '拜仁：主场 4 胜 1 负，禁区压制德甲顶级；近 5 场 17 入 6 失，安联抢分稳。',
      awayForm: '多特：客场 3 胜 2 负，火力维持；近 5 场 13 入 10 失，德比客场仍会主动提速。',
      attack: '拜仁高位逼抢 + 边路内切；多特转换与肋部直塞威胁大，总进球仍可期。',
      defense: '拜仁协防尚可但定位球二点偶弱；多特客场失球不少，深盘下难全场零封拜仁。',
      motivation: '德甲争冠/国家德比，拜仁主场必须建立优势，战术上主动控场。',
      pace: '临场建议：亚盘维持 -0.5 拜仁低水可跟；大小若升至 3.5 且大球低水可搭配大2.5。走地须防早段红牌改变节奏。',
    },
  },
  {
    slug: 'psg-vs-marseille-2026-05-26',
    date: '2026-05-26',
    kickoff: '03:45',
    league: { slug: 'ligue-1', nameZh: '法甲' },
    homeTeam: { slug: 'psg', nameZh: '巴黎圣日耳曼', abbr: 'PSG' },
    awayTeam: { slug: 'marseille', nameZh: '马赛', abbr: 'OM' },
    prediction: '巴黎 -1',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 25,
    venueZh: '王子公园球场',
    round: '国家德比',
    pickType: 'home',
    lineOpen: '巴黎 -0.75',
    lineCurrent: '巴黎 -1',
    ouTrend: 'up',
    modelWinRate: 71,
    summary: '法甲国家德比，巴黎主场深盘升档，资金承接主队方向。',
    content: {
      homeForm: '巴黎：主场 5 胜，前场创造力法甲顶格；近 5 场 15 入 4 失，王子公园压制力足。',
      awayForm: '马赛：客场 2 胜 3 负，对抗强硬但防线速度是隐患；近 5 场 9 入 12 失，客场失球偏多。',
      attack: '巴黎边路个人能力与中路插上；马赛依赖反击与定位球，面对高压时出球质量下降。',
      defense: '巴黎主场零封率尚可；马赛客场中卫回追与肋部保护连场被打穿。',
      motivation: '法甲国家德比 + 争冠动机，巴黎主场不会保守。',
      pace: '临场建议：深盘 -1 下若巴黎低水 ≤0.88 可跟；若退至 -0.75 且升水则减仓。大小球临场若急升至 3.25 需防「升盘诱大」。',
    },
  },
  {
    slug: 'liverpool-vs-man-united-2026-05-26',
    date: '2026-05-26',
    kickoff: '20:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 26,
    venueZh: '安菲尔德',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 75,
    modelWinRate: 74,
    picks: ['👉 方向：大 2.5', '👉 方向：利物浦 -0.75'],
    summary: '双红会节奏快、交锋大球率高，大小升盘首选大2.5。',
    content: {
      homeForm: '利物浦：主场 4 胜 1 负，前场压迫与转换效率英超顶格；近 5 场 15 入 6 失。',
      awayForm: '曼联：客场 2 胜 2 负 1 和，终结效率回升但防线松动；近 5 场 11 入 10 失。',
      attack: '利物浦高位逼抢 + 两翼提速；曼联远射与定位球占比升，双方均有破门路径。',
      defense: '利物浦仅 2 场零封，高位线身后空档需防；曼联客场连场有失球，支撑大球逻辑。',
      motivation: '英超双红会，双方均需抢分，临场资金或推高热门盘与大球方向。',
      pace: '临场建议：大小 3 球大球低水可跟；若曼联临场确认主力中卫缺阵，可加重利物浦让球方向。走地早段进球后不宜追小球。',
    },
  },
  {
    slug: 'atletico-vs-sevilla-2026-05-26',
    date: '2026-05-26',
    kickoff: '01:00',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'atletico', nameZh: '马竞', abbr: 'ATM' },
    awayTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    prediction: '马竞 -0.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 27,
    venueZh: '万达大都会球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '马竞 -0.25',
    lineCurrent: '马竞 -0.5',
    ouTrend: 'stable',
    modelWinRate: 64,
    summary: '马竞主场防守体系成熟，塞维利亚客场进攻乏力，跟主队浅盘。',
    content: {
      homeForm: '马竞：主场 3 胜 2 负，低位防守 + 反击犀利；近 5 场 8 入 5 失，主场节奏可控。',
      awayForm: '塞维利亚：客场 1 胜 4 负，创造力不足；近 5 场 6 入 11 失，客场抢分困难。',
      attack: '马竞定位球与反击效率高；塞维利亚依赖边路传中，面对密集防守终结一般。',
      defense: '马竞主场协防西甲顶级，零封率偏高；塞维利亚客场肋部隐患大。',
      motivation: '西甲抢四/欧战席位，马竞主场战意与历史盘口支持让球方。',
      pace: '临场建议：亚盘 -0.5 马竞低水可跟；大小球若维持 2.25 小球低水则不宜硬跟大球。若塞维利亚临场变阵强攻，走地再评估。',
    },
  },
  {
    slug: 'juventus-vs-napoli-2026-05-26',
    date: '2026-05-26',
    kickoff: '02:00',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 28,
    venueZh: '安联球场（都灵）',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 68,
    modelWinRate: 67,
    summary: '意甲强强对话，那不勒斯客场火力足，大小升盘跟大2.5。',
    content: {
      homeForm: '尤文：主场 3 胜 1 平 1 负，防守体系成熟；近 5 场 9 入 6 失，主场节奏偏稳。',
      awayForm: '那不勒斯：客场 3 胜 2 负，锋线转化率维持高位；近 5 场 13 入 8 失，客场不保守。',
      attack: '尤文定位球与边路传中；那不勒斯肋部渗透 + 快速转换，双方均有破门可能。',
      defense: '尤文主场零封率尚可但高位线偶被直塞打穿；那不勒斯客场失球不算少。',
      motivation: '意甲争二/欧冠席位关键战，客队需抢分，总进球方向更值得跟进。',
      pace: '临场建议：大小由 2.5 升至 2.75 且大球低水可跟；若临场回落 2.5 且大球升水则观望。赛果盘尤文平手低水时可小注主胜。',
    },
  },
  {
    slug: 'roma-vs-lazio-2026-05-26',
    date: '2026-05-26',
    kickoff: '02:45',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'roma', nameZh: '罗马', abbr: 'ROM' },
    awayTeam: { slug: 'lazio', nameZh: '拉齐奥', abbr: 'LAZ' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 29,
    venueZh: '奥林匹克球场',
    round: '罗马德比',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 70,
    modelWinRate: 65,
    summary: '罗马德比情绪高、历史大球率不低，大小升盘跟大2.5。',
    content: {
      homeForm: '罗马：主场 3 胜 2 负，进攻创造力尚可；近 5 场 10 入 8 失，奥林匹克主场战意足。',
      awayForm: '拉齐奥：客场 2 胜 3 负，反击威胁大；近 5 场 11 入 10 失，德比客场不会闷守。',
      attack: '罗马中路渗透 + 定位球；拉齐奥转换与边路提速，双方破门路径清晰。',
      defense: '罗马主场防线偶有失球；拉齐奥客场协防波动——德比「能攻难守」逻辑成立。',
      motivation: '罗马德比 + 欧战席位争夺，平局对双方均不理想。',
      pace: '临场建议：大小 2.75 大球低水可跟；若早段 0-0 且大小未降盘，下半场可保留走地大球。亚盘平手盘下观望，勿与大小方向硬绑。',
    },
  },
];

/** 每日 SEO 热门 ×20（2026-05-29） */
const SEO_DAILY_2026_05_29: SeoAnalysisMatchSeed[] = [
  {
    slug: 'man-city-vs-chelsea-2026-05-29',
    date: '2026-05-29',
    kickoff: '23:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    awayTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    prediction: '曼城 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 30,
    venueZh: '伊蒂哈德球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '曼城 -0.5',
    lineCurrent: '曼城 -0.75',
    ouTrend: 'stable',
    modelWinRate: 74,
    summary: '曼城主场盘口升档，切尔西客场防线波动，跟主队方向。',
    content: {
      homeForm: '曼城：主场 4 胜 1 负，控球压制力顶级；近 5 场 16 入 5 失。',
      awayForm: '切尔西：客场 2 胜 2 负 1 和；近 5 场 9 入 11 失，客场失球偏多。',
      attack: '曼城中路渗透效率高；切尔西依赖转换，面对高压出球质量下降。',
      defense: '曼城主场零封率尚可；切尔西肋部与反击隐患大。',
      motivation: '英超争冠关键战，曼城主场必须拿分。',
      pace: '临场建议：亚盘维持 -0.75 主队低水可跟；退至 -0.5 且升水则减仓。大小临场回落至 2.75 且大球升水则观望。',
    },
  },
  {
    slug: 'arsenal-vs-tottenham-2026-05-29',
    date: '2026-05-29',
    kickoff: '22:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 31,
    venueZh: '酋长球场',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 73,
    modelWinRate: 72,
    summary: '北伦敦德比大球率高，大小升盘首选大2.5。',
    content: {
      homeForm: '阿森纳：主场 3 胜 1 负；近 5 场 11 入 7 失，酋长球场战意足。',
      awayForm: '热刺：客场 3 胜 2 负；近 5 场 12 入 9 失，德比不保守。',
      attack: '阿森纳两翼内切威胁大；热刺转换效率上游，双方破门路径清晰。',
      defense: '阿森纳高位线有风险；热刺客场失球不少，支撑大球。',
      motivation: '北伦敦德比 + 争四战意，节奏不宜闷战。',
      pace: '临场建议：大小 3 球大球 ≤0.90 可跟；早段进球可保留走地大球。阿森纳退至 -0.25 升水则以大小为主。',
    },
  },
  {
    slug: 'liverpool-vs-man-united-2026-05-29',
    date: '2026-05-29',
    kickoff: '20:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 32,
    venueZh: '安菲尔德',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 75,
    modelWinRate: 74,
    summary: '双红会交锋大球率高，大小升盘跟大2.5。',
    content: {
      homeForm: '利物浦：主场 4 胜 1 负；近 5 场 15 入 6 失，压迫效率顶格。',
      awayForm: '曼联：客场 2 胜 2 负 1 和；近 5 场 11 入 10 失，防线松动。',
      attack: '利物浦两翼提速 + 转换；曼联远射与定位球占比升。',
      defense: '利物浦零封偏少；曼联客场连场有失球。',
      motivation: '双红会抢分战，资金或推高热门与大球。',
      pace: '临场建议：大小 3 球大球低水可跟；曼联中卫缺阵则加重利物浦让球。走地早段进球不宜追小。',
    },
  },
  {
    slug: 'real-madrid-vs-barcelona-2026-05-29',
    date: '2026-05-29',
    kickoff: '04:00',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 33,
    venueZh: '伯纳乌',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 78,
    modelWinRate: 76,
    summary: '国家德比大球率高，伯纳乌夜战升盘跟大2.5。',
    content: {
      homeForm: '皇马：主场 4 胜 1 和；近 5 场 14 入 4 失，伯纳乌压制力强。',
      awayForm: '巴萨：客场 3 胜 2 负；近 5 场 13 入 6 失，德比战意足。',
      attack: '皇马边路提速；巴萨肋部渗透，双方 xG 稳定。',
      defense: '皇马高位线有风险；巴萨客场失球不少，支撑大球。',
      motivation: '西甲争冠国家德比，节奏偏快。',
      pace: '临场建议：大小 3 球大球低水可跟；退至 2.75 升水则观望。完整水位 TG 赛前更新。',
    },
  },
  {
    slug: 'atletico-vs-sevilla-2026-05-29',
    date: '2026-05-29',
    kickoff: '01:00',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'atletico', nameZh: '马竞', abbr: 'ATM' },
    awayTeam: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    prediction: '马竞 -0.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 34,
    venueZh: '万达大都会球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '马竞 -0.25',
    lineCurrent: '马竞 -0.5',
    ouTrend: 'stable',
    modelWinRate: 64,
    summary: '马竞主场防守成熟，塞维利亚客场乏力，跟主队浅盘。',
    content: {
      homeForm: '马竞：主场 3 胜 2 负；近 5 场 8 入 5 失，节奏可控。',
      awayForm: '塞维利亚：客场 1 胜 4 负；近 5 场 6 入 11 失。',
      attack: '马竞反击与定位球效率高；塞维利亚终结一般。',
      defense: '马竞主场协防顶级；塞维利亚客场肋部隐患大。',
      motivation: '西甲抢四战，马竞主场盘口支持。',
      pace: '临场建议：-0.5 马竞低水可跟；大小 2.25 小球低水不宜硬跟大球。',
    },
  },
  {
    slug: 'inter-vs-ac-milan-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:45',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    prediction: '国米 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 35,
    venueZh: '梅阿查球场',
    round: '第38轮',
    pickType: 'home',
    modelWinRate: 66,
    summary: '米兰德比，国米主场近况与盘口同向。',
    content: {
      homeForm: '国米：主场 4 胜 1 负；近 5 场 12 入 5 失。',
      awayForm: 'AC米兰：客场 2 胜 2 负 1 和；近 5 场 8 入 9 失。',
      attack: '国米中路渗透稳定；米兰依赖反击，质量起伏。',
      defense: '国米主场协防尚可；米兰客场肋部易被打穿。',
      motivation: '米兰德比，国米主场战意更足。',
      pace: '临场建议：国米低水可跟；升为高水且大小降盘则观望。确认中卫缺阵再定仓位。',
    },
  },
  {
    slug: 'juventus-vs-napoli-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:00',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    awayTeam: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 36,
    venueZh: '安联球场（都灵）',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 68,
    modelWinRate: 67,
    summary: '那不勒斯客场火力足，大小升盘跟大2.5。',
    content: {
      homeForm: '尤文：主场 3 胜 1 平 1 负；近 5 场 9 入 6 失。',
      awayForm: '那不勒斯：客场 3 胜 2 负；近 5 场 13 入 8 失。',
      attack: '尤文定位球威胁；那不勒斯肋部渗透 + 转换犀利。',
      defense: '尤文偶被直塞打穿；那不勒斯客场失球不少。',
      motivation: '意甲争二关键战，客队需抢分。',
      pace: '临场建议：2.75 大球低水可跟；回落 2.5 升水则观望。尤文平手低水可小注主胜。',
    },
  },
  {
    slug: 'roma-vs-lazio-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:45',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'roma', nameZh: '罗马', abbr: 'ROM' },
    awayTeam: { slug: 'lazio', nameZh: '拉齐奥', abbr: 'LAZ' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 37,
    venueZh: '奥林匹克球场',
    round: '罗马德比',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 70,
    modelWinRate: 65,
    summary: '罗马德比历史大球率不低，跟大2.5。',
    content: {
      homeForm: '罗马：主场 3 胜 2 负；近 5 场 10 入 8 失。',
      awayForm: '拉齐奥：客场 2 胜 3 负；近 5 场 11 入 10 失。',
      attack: '罗马定位球 + 中路渗透；拉齐奥转换威胁大。',
      defense: '双方防线波动，德比支撑大球。',
      motivation: '罗马德比 + 欧战席位争夺。',
      pace: '临场建议：2.75 大球低水可跟；0-0 早段且未降盘可保留下半场大球。亚盘平手观望。',
    },
  },
  {
    slug: 'psg-vs-marseille-2026-05-29',
    date: '2026-05-29',
    kickoff: '03:45',
    league: { slug: 'ligue-1', nameZh: '法甲' },
    homeTeam: { slug: 'psg', nameZh: '巴黎圣日耳曼', abbr: 'PSG' },
    awayTeam: { slug: 'marseille', nameZh: '马赛', abbr: 'OM' },
    prediction: '巴黎 -1',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 38,
    venueZh: '王子公园球场',
    round: '国家德比',
    pickType: 'home',
    lineOpen: '巴黎 -0.75',
    lineCurrent: '巴黎 -1',
    modelWinRate: 71,
    summary: '法甲国家德比，巴黎深盘升档跟主队。',
    content: {
      homeForm: '巴黎：主场 5 胜；近 5 场 15 入 4 失，压制力足。',
      awayForm: '马赛：客场 2 胜 3 负；近 5 场 9 入 12 失。',
      attack: '巴黎边路个人能力顶级；马赛依赖反击。',
      defense: '巴黎主场零封尚可；马赛客场回追是隐患。',
      motivation: '国家德比 + 争冠，巴黎主场不保守。',
      pace: '临场建议：-1 低水 ≤0.88 可跟；退 -0.75 升水则减仓。大小急升 3.25 防诱大。',
    },
  },
  {
    slug: 'bayern-vs-dortmund-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:30',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    prediction: '拜仁 -0.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 39,
    venueZh: '安联球场',
    round: '第34轮',
    pickType: 'home',
    lineOpen: '拜仁 -0.25',
    lineCurrent: '拜仁 -0.5',
    ouTrend: 'up',
    modelWinRate: 73,
    summary: '国家德比拜仁升盘，安联跟让球方。',
    content: {
      homeForm: '拜仁：主场 4 胜 1 负；近 5 场 17 入 6 失。',
      awayForm: '多特：客场 3 胜 2 负；近 5 场 13 入 10 失。',
      attack: '拜仁高位逼抢；多特转换威胁大，总进球可期。',
      defense: '拜仁协防偶弱；多特客场难零封拜仁。',
      motivation: '德甲争冠国家德比，拜仁主场抢分。',
      pace: '临场建议：-0.5 拜仁低水可跟；大小升 3.5 大球低水可配大2.5。防早段红牌。',
    },
  },
  {
    slug: 'arsenal-vs-man-city-2026-05-29',
    date: '2026-05-29',
    kickoff: '23:30',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    awayTeam: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: true,
    homepageOrder: 40,
    venueZh: '酋长球场',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 75,
    modelWinRate: 75,
    summary: '榜首大战对攻格局，大小升盘首选大2.5。',
    content: {
      homeForm: '阿森纳：主场 3 胜 1 负；近 5 场 11 入 7 失，不保守。',
      awayForm: '曼城：客场火力维持；近 5 场 14 入 7 失。',
      attack: '阿森纳两翼内切；曼城肋部渗透，双方 xG 高。',
      defense: '双方高位线均有空档，支撑大球。',
      motivation: '英超榜首直接对话，不宜闷战。',
      pace: '临场建议：3 球大球低水可跟；阿森纳退 -0.25 升水则以大小为主。TG 赛前确认阵容。',
    },
  },
  {
    slug: 'chelsea-vs-tottenham-2026-05-29',
    date: '2026-05-29',
    kickoff: '22:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    awayTeam: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    prediction: '大 2.5',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 41,
    venueZh: '斯坦福桥',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 71,
    modelWinRate: 70,
    summary: '伦敦德比双方攻强守弱，跟大2.5。',
    content: {
      homeForm: '切尔西：主场 3 胜 2 负；近 5 场 10 入 9 失。',
      awayForm: '热刺：客场 3 胜 2 负；近 5 场 12 入 9 失。',
      attack: '切尔西边路传中；热刺转换犀利。',
      defense: '切尔西主场失球不少；热刺客场防线波动。',
      motivation: '伦敦德比 + 欧战席位，节奏偏快。',
      pace: '临场建议：2.75 大球低水可跟；降 2.5 大球升水则观望。走地早段有球可保留大球。',
    },
  },
  {
    slug: 'liverpool-vs-arsenal-2026-05-29',
    date: '2026-05-29',
    kickoff: '21:00',
    league: { slug: 'epl', nameZh: '英超' },
    homeTeam: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    awayTeam: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    prediction: '利物浦 0',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 42,
    venueZh: '安菲尔德',
    round: '第38轮',
    pickType: 'home',
    modelWinRate: 68,
    summary: '安菲尔德近况占优，平手盘跟利物浦。',
    content: {
      homeForm: '利物浦：主场 4 胜 1 负；近 5 场 15 入 6 失。',
      awayForm: '阿森纳：客场 3 胜 2 负；近 5 场 12 入 6 失。',
      attack: '利物浦压迫 + 转换顶格；阿森纳肋部渗透稳定。',
      defense: '利物浦高位线有风险；阿森纳客场失球不多但速度考验大。',
      motivation: '争冠/抢二关键战，利物浦主场战意足。',
      pace: '临场建议：利物浦低水可跟；若升水且大小降盘改观望。可搭配大2.5作副线。',
    },
  },
  {
    slug: 'real-madrid-vs-atletico-2026-05-29',
    date: '2026-05-29',
    kickoff: '03:30',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    awayTeam: { slug: 'atletico', nameZh: '马竞', abbr: 'ATM' },
    prediction: '皇马 -0.25',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 43,
    venueZh: '伯纳乌',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '平手',
    lineCurrent: '皇马 -0.25',
    ouTrend: 'stable',
    modelWinRate: 63,
    summary: '马德里德比，皇马主场浅盘升档跟小胜。',
    content: {
      homeForm: '皇马：主场 4 胜 1 和；近 5 场 14 入 4 失。',
      awayForm: '马竞：客场 2 胜 3 负；近 5 场 7 入 6 失，防守反击为主。',
      attack: '皇马边路压制；马竞反击效率高但创造波动。',
      defense: '皇马主场协防尚可；马竞客场节奏慢，小球属性强。',
      motivation: '西甲争冠马德里德比，皇马主场需抢分。',
      pace: '临场建议：-0.25 皇马低水可跟；大小 2.25 小球热则主跟赛果、副观望大小。0-0 半场慎追大球。',
    },
  },
  {
    slug: 'barcelona-vs-real-sociedad-2026-05-29',
    date: '2026-05-29',
    kickoff: '03:00',
    league: { slug: 'la-liga', nameZh: '西甲' },
    homeTeam: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    awayTeam: { slug: 'real-sociedad', nameZh: '皇家社会', abbr: 'RSO' },
    prediction: '巴萨 -1',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 44,
    venueZh: '诺坎普',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '巴萨 -0.75',
    lineCurrent: '巴萨 -1',
    ouTrend: 'stable',
    modelWinRate: 72,
    summary: '巴萨主场深盘升档，皇家社会客场防守一般。',
    content: {
      homeForm: '巴萨：主场 4 胜 1 负；近 5 场 13 入 6 失，控球压制稳定。',
      awayForm: '皇家社会：客场 2 胜 3 负；近 5 场 8 入 10 失。',
      attack: '巴萨肋部渗透 + 两翼提速；社会依赖边路，终结效率一般。',
      defense: '巴萨高位线偶被打穿；社会客场失球偏多。',
      motivation: '西甲争冠，诺坎普必须拿满三分。',
      pace: '临场建议：-1 巴萨低水可跟；退 -0.75 升水减仓。大小 3 球可观望勿硬跟大球。',
    },
  },
  {
    slug: 'bayern-vs-rb-leipzig-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:30',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    homeTeam: { slug: 'bayern', nameZh: '拜仁', abbr: 'BAY' },
    awayTeam: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    prediction: '拜仁 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 45,
    venueZh: '安联球场',
    round: '第34轮',
    pickType: 'home',
    lineOpen: '拜仁 -0.5',
    lineCurrent: '拜仁 -0.75',
    ouTrend: 'up',
    modelWinRate: 74,
    summary: '拜仁主场对莱比锡盘口升档，跟主队。',
    content: {
      homeForm: '拜仁：主场 4 胜 1 负；近 5 场 17 入 6 失，禁区压制顶级。',
      awayForm: '莱比锡：客场 3 胜 2 负；近 5 场 11 入 9 失，高位压迫风格。',
      attack: '拜仁边路内切 + 中路插上；莱比锡转换快，对攻可期。',
      defense: '拜仁协防偶弱；莱比锡客场失球不少。',
      motivation: '德甲争冠关键战，拜仁主场建立优势。',
      pace: '临场建议：-0.75 低水可跟；大小升 3.5 可配大2.5。莱比锡早段高压需注意走地。',
    },
  },
  {
    slug: 'ac-milan-vs-juventus-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:45',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    awayTeam: { slug: 'juventus', nameZh: '尤文', abbr: 'JUV' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 46,
    venueZh: '圣西罗',
    round: '第38轮',
    pickType: 'over',
    lineOpen: '2.25',
    lineCurrent: '2.5',
    ouTrend: 'up',
    over25Prob: 66,
    modelWinRate: 66,
    summary: '意甲焦点战，大小升盘跟大2.5。',
    content: {
      homeForm: 'AC米兰：主场 3 胜 2 负；近 5 场 9 入 8 失。',
      awayForm: '尤文：客场 2 胜 2 负 1 和；近 5 场 8 入 7 失。',
      attack: '米兰边路传中；尤文定位球 + 反击有威胁。',
      defense: '米兰主场防线波动；尤文客场偏稳但非零封型。',
      motivation: '争四/欧冠席位，双方需抢分。',
      pace: '临场建议：2.5 大球低水可跟；维持 2.25 小球热则观望。圣西罗夜战防闷战突变。',
    },
  },
  {
    slug: 'inter-vs-roma-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:00',
    league: { slug: 'serie-a', nameZh: '意甲' },
    homeTeam: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    awayTeam: { slug: 'roma', nameZh: '罗马', abbr: 'ROM' },
    prediction: '国米 -0.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 47,
    venueZh: '梅阿查球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '国米 -0.25',
    lineCurrent: '国米 -0.5',
    ouTrend: 'stable',
    modelWinRate: 67,
    summary: '国米主场实力差明显，浅盘升档跟主队。',
    content: {
      homeForm: '国米：主场 4 胜 1 负；近 5 场 12 入 5 失，攻防均衡。',
      awayForm: '罗马：客场 2 胜 3 负；近 5 场 9 入 10 失。',
      attack: '国米中路渗透稳定；罗马定位球有威胁但创造波动。',
      defense: '国米主场协防尚可；罗马客场失球偏多。',
      motivation: '意甲争冠/抢二，国米主场必须拿分。',
      pace: '临场建议：-0.5 国米低水可跟；罗马变阵强攻时走地再评估大小。TG 更新阵容。',
    },
  },
  {
    slug: 'psg-vs-monaco-2026-05-29',
    date: '2026-05-29',
    kickoff: '03:00',
    league: { slug: 'ligue-1', nameZh: '法甲' },
    homeTeam: { slug: 'psg', nameZh: '巴黎圣日耳曼', abbr: 'PSG' },
    awayTeam: { slug: 'monaco', nameZh: '摩纳哥', abbr: 'MON' },
    prediction: '巴黎 -0.75',
    confidence: 'high',
    isHot: true,
    isFocus: false,
    homepageOrder: 48,
    venueZh: '王子公园球场',
    round: '第38轮',
    pickType: 'home',
    lineOpen: '巴黎 -0.5',
    lineCurrent: '巴黎 -0.75',
    ouTrend: 'stable',
    modelWinRate: 72,
    summary: '巴黎主场对摩纳哥盘口升档，跟主队。',
    content: {
      homeForm: '巴黎：主场 5 胜；近 5 场 15 入 4 失，前场创造力顶格。',
      awayForm: '摩纳哥：客场 3 胜 2 负；近 5 场 11 入 9 失，进攻有爆点。',
      attack: '巴黎边路个人能力；摩纳哥转换快，副线可考虑大球。',
      defense: '巴黎主场零封尚可；摩纳哥客场协防波动。',
      motivation: '法甲争冠，王子公园不容失分。',
      pace: '临场建议：-0.75 低水可跟；摩纳哥反击犀利走地慎追深盘。大小 3 球可小注大球。',
    },
  },
  {
    slug: 'dortmund-vs-leverkusen-2026-05-29',
    date: '2026-05-29',
    kickoff: '02:30',
    league: { slug: 'bundesliga', nameZh: '德甲' },
    homeTeam: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    awayTeam: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    prediction: '大 2.5',
    confidence: 'medium',
    isHot: true,
    isFocus: false,
    homepageOrder: 49,
    venueZh: '威斯特法伦球场',
    round: '第34轮',
    pickType: 'over',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 72,
    modelWinRate: 69,
    summary: '德甲对攻大战，大小升盘跟大2.5。',
    content: {
      homeForm: '多特：主场 3 胜 2 负；近 5 场 13 入 10 失，主场火力足。',
      awayForm: '勒沃库森：客场 3 胜 2 负；近 5 场 12 入 8 失，进攻流畅。',
      attack: '多特高压 + 转换；药厂肋部渗透，双方 xG 高。',
      defense: '多特主场失球不少；药厂客场非铁壁，支撑大球。',
      motivation: '德甲抢四/欧冠席位，节奏偏快。',
      pace: '临场建议：3 球大球低水可跟；降 2.75 升水则观望。早段进球可保留走地大球。',
    },
  },
];

/** 每日 SEO 热门（2026-05-30 · 仅 5 场真实赛事） */
const SEO_DAILY_TODAY: SeoAnalysisMatchSeed[] =
  seoArticlesHot20260530.map(seoArticleToSeed);

/**
 * 手动维护的分析场次（优先级高于批量模板同 slug）
 * 批量模板场次在 mock-analyses-batch.ts，由 analysis-registry 自动合并
 */
export const ANALYSIS_MATCHES: DailyAnalysisInput[] = [
  ...SEO_BATCH_1.map(seoBatchToInput),
  ...SEO_BATCH_2.map(seoBatchToInput),
  {
    slug: 'real-madrid-vs-barcelona-2026-05-27',
    home: { slug: 'real-madrid', nameZh: '皇马', abbr: 'RMA' },
    away: { slug: 'barcelona', nameZh: '巴萨', abbr: 'BAR' },
    league: { slug: 'la-liga', nameZh: '西甲' },
    kickoffAt: '2026-05-26T20:00:00.000Z',
    kickoffTimeDisplay: '04:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '皇马：主场 4 胜 1 和，近 5 场 14 入 4 失，伯纳乌压制力仍属西甲顶格；国家德比战意拉满，开场倾向高位逼抢。',
      awayForm:
        '巴萨：客场 3 胜 1 负，锋线转化率稳定但客场失球率偏高；近 5 场 11 入 7 失，需防反击被皇马速度惩罚。',
      attack:
        '皇马边路提速 + 禁区前沿远射威胁大；巴萨控球推进仍能制造 xG，双方破门路径清晰，不利于闷战格局。',
      defense:
        '皇马零封率一般，高位线身后有空档；巴萨客场中卫协防与定位球二点偏弱——德比往往互有进球。',
      motivation: '国家德比：市场热度高，大小球与亚盘临场波动会快于一般联赛场次。',
      pace: '预计上半场即有射门威胁，节奏偏快；早段进球会进一步推高总进球预期。',
    },
    options: {
      confidence: 'high',
      summary: '德比升盘配大球低水，对攻格局概率高于隐含概率',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 0,
      featuredInLatest: true,
      modelWinRate: 78,
      venueZh: '伯纳乌球场',
      round: '第37轮',
      pickType: 'over',
      lineOpen: '3.0',
      lineCurrent: '3.25',
      ouTrend: 'up',
      over25Prob: 78,
      publishedAt: '2026-05-27T06:00:00.000Z',
    },
  },
  {
    slug: 'bayern-vs-dortmund-2026-05-27',
    home: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    away: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    league: { slug: 'bundesliga', nameZh: '德甲' },
    kickoffAt: '2026-05-26T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    direction: '拜仁 -0.75',
    options: {
      confidence: 'high',
      summary: '半一低水配合主场统治力，主胜路径清晰',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 1,
      featuredInLatest: true,
      isFreePublic: true,
      isLiveUpdating: true,
      modelWinRate: 71,
      venueZh: '安联球场',
      round: '第33轮',
      pickType: 'home',
      lineOpen: '3.25',
      lineCurrent: '3.5',
      ouTrend: 'up',
      publishedAt: '2026-05-27T05:00:00.000Z',
    },
  },
  {
    slug: 'arsenal-vs-man-city-2026-05-26',
    home: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '阿森纳：主场 3 胜 1 负，控球压制稳定；近 5 场 11 入 7 失，酋长球场抢分战意足，对阵强队不保守。',
      awayForm:
        '曼城：客场火力维持高位，近 5 场 13 入 8 失；联赛争冠/抢二动机下客场仍会主动控场推进。',
      attack:
        '阿森纳两翼内切 + 萨卡一侧制造威胁；曼城中路渗透与肋部直塞效率高，双方均有稳定进球路径。',
      defense:
        '阿森纳高位线身后偶有被打穿；曼城客场失球不算少，强强对话更支撑大球而非单边零封。',
      motivation: '英超榜首大战：临场资金或同步推高热门盘与大球方向。',
      pace: '开场 15–25 分钟节奏偏快，不宜预期闷战；下半场若比分紧咬，对攻频率仍会维持。',
    },
    options: {
      confidence: 'high',
      summary: '升盘配合大球低水，对攻格局概率高于隐含概率',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 2,
      featuredInLatest: true,
      isLiveUpdating: true,
      modelWinRate: 75,
      venueZh: '酋长球场',
      round: '第38轮',
      pickType: 'over',
      lineOpen: '2.75',
      lineCurrent: '3.0',
      ouTrend: 'up',
      over25Prob: 75,
      publishedAt: '2026-05-26T06:00:00.000Z',
    },
  },
  {
    slug: 'man-united-vs-liverpool-2026-05-25',
    home: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    away: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    direction: '大 2.5',
    content: {
      homeForm:
        '曼联：主场 3 胜 1 和走势，终结效率回升，但高位线身后空档仍易被利用；近 5 场 12 入 6 失，联赛第 6，老特拉福德抢分战意足。',
      awayForm:
        '利物浦：客场 4 胜 1 负，火力英超顶格；近 5 场 14 入 5 失，联赛第 2，争冠/抢二动机强，客场不会保守。',
      attack:
        '曼联近 5 场 12 球，远射与定位球占比升；利物浦近 5 场 14 球，两翼内切 + 中场前插形成稳定 xG，双方均有稳定破门路径。',
      defense:
        '曼联仅 2 场零封，肋部与反击连场被打穿；利物浦客场近 4 场场场有失球，中卫协防与二点保护是短板——「能攻难守」支撑大球逻辑。',
      motivation: '第 38 轮双红会，双方均需抢分；本场为今日重心，临场资金或推高热门盘与大球方向。',
      pace: '预计开场 15–20 分钟进入对攻，上半场即有射门威胁，不宜预期闷战；若早段进球，节奏将进一步加快。',
    },
    options: {
      confidence: 'high',
      picks: ['👉 方向：大 2.5', '👉 方向：利物浦 -0.5'],
      summary:
        '双红会节奏快、交锋大球率高，配合大小升 3 球大球低水，首选大2.5；比分参考 1-2、2-2。完整临场方向（水位确认、阵容与走地）开赛前会在 TG 更新。',
      isHot: true,
      isFocus: true,
      showOnHomepage: true,
      homepageOrder: 3,
      isFreePublic: true,
      isLiveUpdating: true,
      modelWinRate: 72,
      venueZh: '老特拉福德',
      round: '第38轮',
      pickType: 'over',
      lineOpen: '2.75',
      lineCurrent: '3.0',
      ouTrend: 'up',
      over25Prob: 72,
      publishedAt: '2026-05-25T06:00:00.000Z',
    },
  },
  {
    slug: 'crystal-palace-vs-arsenal-2026-05-25',
    home: { slug: 'crystal-palace', nameZh: '水晶宮', abbr: 'CRY' },
    away: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    league: { slug: 'epl', nameZh: '英超' },
    kickoffAt: '2026-05-25T15:00:00.000Z',
    kickoffTimeDisplay: '23:00',
    direction: '客胜',
    options: {
      confidence: 'medium',
      summary: '战意与实力差支撑客队，浅盘小胜格局',
      isHot: true,
      showOnHomepage: true,
      homepageOrder: 4,
      featuredInLatest: false,
      isLiveUpdating: true,
      modelWinRate: 58,
      venueZh: 'Selhurst Park',
      round: '第38轮',
      pickType: 'away',
      ouTrend: 'stable',
      lineOpen: '2.5',
      lineCurrent: '2.5',
      publishedAt: '2026-05-24T10:00:00.000Z',
    },
  },
  ...SEO_DAILY_2026_05_25.map(seoBatchToInput),
  ...SEO_DAILY_2026_05_26.map(seoBatchToInput),
  ...SEO_DAILY_2026_05_29.map(seoBatchToInput),
  ...SEO_DAILY_TODAY.map(seoBatchToInput),
];

/** SEO 批次原始数据（供查阅 / 导出） */
export {
  SEO_BATCH_1,
  SEO_BATCH_2,
  SEO_DAILY_2026_05_25,
  SEO_DAILY_2026_05_26,
  SEO_DAILY_2026_05_29,
  SEO_DAILY_TODAY,
};
