import { buildBatchAnalysis, type BatchMatchSeed } from '@/lib/analysis-page-builder';
import type { PreMatchAnalysisDetail } from '@/types/analysis';
import type { DailyAnalysisInput } from '@/types/daily-analysis';

// =============================================================================
//  批量分析场次模板（历史场次 · 由 analysis-registry 自动合并）
//  日常新增请只改 src/lib/analysis-matches.ts → ANALYSIS_MATCHES
// =============================================================================

export const BATCH_MATCH_SEEDS: BatchMatchSeed[] = [
  // —— 英超 ×4 ——
  {
    slug: 'liverpool-vs-man-city-2026-05-28',
    kickoffAt: '2026-05-28T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '安菲尔德',
    round: '第38轮',
    home: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 74,
    modelWinRate: 74,
    isHot: true,
    pickType: 'over',
    homeRank: 2,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '平手',
    asianCurrent: '利物浦 -0.25',
    asianTrend: 'up',
    publishedAt: '2026-05-28T06:00:00.000Z',
  },
  {
    slug: 'chelsea-vs-arsenal-2026-05-28',
    kickoffAt: '2026-05-28T16:30:00.000Z',
    kickoffTimeDisplay: '00:30',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '斯坦福桥',
    round: '第38轮',
    home: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    away: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    direction: '阿森纳 -0.25',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 55,
    modelWinRate: 62,
    isHot: true,
    pickType: 'away',
    homeRank: 5,
    awayRank: 1,
    h2hHome: 1,
    h2hDraw: 2,
    h2hAway: 2,
    over25Rate: 60,
    avgGoals: 2.6,
    asianOpen: '切尔西 +0.25',
    asianCurrent: '切尔西 +0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-28T05:00:00.000Z',
  },
  {
    slug: 'man-united-vs-man-city-2026-05-29',
    kickoffAt: '2026-05-29T11:30:00.000Z',
    kickoffTimeDisplay: '19:30',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '老特拉福德',
    round: '第38轮',
    home: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '曼城 -0.75',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '2.75',
    ouTrend: 'stable',
    over25Prob: 68,
    modelWinRate: 70,
    isFocus: true,
    pickType: 'away',
    homeRank: 6,
    awayRank: 3,
    h2hHome: 0,
    h2hDraw: 1,
    h2hAway: 4,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '曼联 +0.75',
    asianCurrent: '曼联 +0.75',
    asianTrend: 'down',
    publishedAt: '2026-05-29T04:00:00.000Z',
  },
  {
    slug: 'tottenham-vs-newcastle-2026-05-29',
    kickoffAt: '2026-05-29T14:00:00.000Z',
    kickoffTimeDisplay: '22:00',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '托特纳姆热刺球场',
    round: '第38轮',
    home: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    away: { slug: 'newcastle', nameZh: '纽卡斯尔', abbr: 'NEW' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 66,
    modelWinRate: 66,
    pickType: 'over',
    homeRank: 7,
    awayRank: 8,
    h2hHome: 3,
    h2hDraw: 0,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '热刺 -0.25',
    asianCurrent: '热刺 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-29T05:00:00.000Z',
  },
  // —— 欧冠 ×4 ——
  {
    slug: 'real-madrid-vs-man-city-2026-05-29',
    kickoffAt: '2026-05-29T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '伯纳乌球场',
    round: '半决赛次回合',
    home: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 76,
    modelWinRate: 76,
    isHot: true,
    isFocus: true,
    pickType: 'over',
    homeRank: 1,
    awayRank: 2,
    h2hHome: 3,
    h2hDraw: 0,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.2,
    asianOpen: '皇马 -0.25',
    asianCurrent: '皇马 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-29T06:00:00.000Z',
  },
  {
    slug: 'barcelona-vs-bayern-2026-05-30',
    kickoffAt: '2026-05-30T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '诺坎普球场',
    round: '半决赛次回合',
    home: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 78,
    modelWinRate: 78,
    isHot: true,
    pickType: 'over',
    homeRank: 2,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 100,
    avgGoals: 3.6,
    asianOpen: '巴萨 -0.25',
    asianCurrent: '平手',
    asianTrend: 'down',
    publishedAt: '2026-05-30T06:00:00.000Z',
  },
  {
    slug: 'liverpool-vs-real-madrid-2026-05-30',
    kickoffAt: '2026-05-30T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '安菲尔德',
    round: '8强次回合',
    home: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    away: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    direction: '利物浦 -0.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '2.75',
    ouTrend: 'stable',
    over25Prob: 70,
    modelWinRate: 65,
    pickType: 'home',
    homeRank: 4,
    awayRank: 5,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '利物浦 -0.25',
    asianCurrent: '利物浦 -0.5',
    asianTrend: 'up',
    publishedAt: '2026-05-30T05:00:00.000Z',
  },
  {
    slug: 'arsenal-vs-bayern-2026-05-31',
    kickoffAt: '2026-05-31T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '酋长球场',
    round: '8强次回合',
    home: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 72,
    modelWinRate: 72,
    isHot: true,
    pickType: 'over',
    homeRank: 6,
    awayRank: 3,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.2,
    asianOpen: '阿森纳 +0.25',
    asianCurrent: '阿森纳 +0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-31T06:00:00.000Z',
  },
  // —— 西甲 ×4 ——
  {
    slug: 'atletico-vs-barcelona-2026-05-31',
    kickoffAt: '2026-05-31T16:15:00.000Z',
    kickoffTimeDisplay: '00:15',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '万达大都会球场',
    round: '第37轮',
    home: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    away: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    direction: '小 2.5',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.25',
    ouTrend: 'down',
    over25Prob: 42,
    modelWinRate: 58,
    pickType: 'under',
    homeRank: 4,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 40,
    avgGoals: 2.2,
    asianOpen: '马竞 0',
    asianCurrent: '马竞 0',
    asianTrend: 'stable',
    publishedAt: '2026-05-31T05:00:00.000Z',
  },
  {
    slug: 'real-madrid-vs-sevilla-2026-06-01',
    kickoffAt: '2026-06-01T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '伯纳乌球场',
    round: '第37轮',
    home: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    away: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    direction: '皇马 -1',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.0',
    ouTrend: 'stable',
    over25Prob: 68,
    modelWinRate: 73,
    isHot: true,
    pickType: 'home',
    homeRank: 2,
    awayRank: 9,
    h2hHome: 4,
    h2hDraw: 1,
    h2hAway: 0,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '皇马 -1',
    asianCurrent: '皇马 -1',
    asianTrend: 'stable',
    publishedAt: '2026-06-01T06:00:00.000Z',
  },
  {
    slug: 'barcelona-vs-valencia-2026-06-01',
    kickoffAt: '2026-06-01T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '诺坎普球场',
    round: '第37轮',
    home: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    away: { slug: 'valencia', nameZh: '瓦伦西亚', abbr: 'VAL' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 76,
    modelWinRate: 76,
    pickType: 'over',
    homeRank: 3,
    awayRank: 12,
    h2hHome: 4,
    h2hDraw: 1,
    h2hAway: 0,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '巴萨 -1.25',
    asianCurrent: '巴萨 -1.5',
    asianTrend: 'up',
    publishedAt: '2026-06-01T05:00:00.000Z',
  },
  {
    slug: 'villarreal-vs-real-madrid-2026-06-02',
    kickoffAt: '2026-06-02T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '陶瓷球场',
    round: '第37轮',
    home: { slug: 'villarreal', nameZh: '比利亚雷亚尔', abbr: 'VIL' },
    away: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 70,
    modelWinRate: 68,
    pickType: 'over',
    homeRank: 5,
    awayRank: 2,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '黄潜 +0.5',
    asianCurrent: '黄潜 +0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-02T06:00:00.000Z',
  },
  // —— 德甲 ×4 ——
  {
    slug: 'leverkusen-vs-bayern-2026-06-02',
    kickoffAt: '2026-06-02T16:30:00.000Z',
    kickoffTimeDisplay: '00:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '拜耳球场',
    round: '第33轮',
    home: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '拜仁 -0.5',
    confidence: 'high',
    lineOpen: '3.25',
    lineCurrent: '3.5',
    ouTrend: 'up',
    over25Prob: 75,
    modelWinRate: 72,
    isHot: true,
    pickType: 'away',
    homeRank: 2,
    awayRank: 1,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.6,
    asianOpen: '勒沃库森 +0.5',
    asianCurrent: '勒沃库森 +0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-02T05:00:00.000Z',
  },
  {
    slug: 'dortmund-vs-rb-leipzig-2026-06-03',
    kickoffAt: '2026-06-03T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '威斯特法伦球场',
    round: '第33轮',
    home: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    away: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 77,
    modelWinRate: 77,
    isHot: true,
    pickType: 'over',
    homeRank: 4,
    awayRank: 5,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '多特 -0.25',
    asianCurrent: '多特 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-06-03T06:00:00.000Z',
  },
  {
    slug: 'bayern-vs-rb-leipzig-2026-06-03',
    kickoffAt: '2026-06-03T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '安联球场',
    round: '第33轮',
    home: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    away: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    direction: '拜仁 -0.75',
    confidence: 'high',
    lineOpen: '3.5',
    lineCurrent: '3.5',
    ouTrend: 'stable',
    over25Prob: 72,
    modelWinRate: 74,
    isFocus: true,
    pickType: 'home',
    homeRank: 1,
    awayRank: 5,
    h2hHome: 4,
    h2hDraw: 0,
    h2hAway: 1,
    over25Rate: 80,
    avgGoals: 3.8,
    asianOpen: '拜仁 -0.75',
    asianCurrent: '拜仁 -0.75',
    asianTrend: 'stable',
    publishedAt: '2026-06-03T05:00:00.000Z',
  },
  {
    slug: 'frankfurt-vs-dortmund-2026-06-04',
    kickoffAt: '2026-06-04T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '德意志银行公园',
    round: '第33轮',
    home: { slug: 'frankfurt', nameZh: '法兰克福', abbr: 'SGE' },
    away: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 69,
    modelWinRate: 67,
    pickType: 'over',
    homeRank: 6,
    awayRank: 4,
    h2hHome: 2,
    h2hDraw: 0,
    h2hAway: 3,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '法兰克福 +0.25',
    asianCurrent: '法兰克福 0',
    asianTrend: 'up',
    publishedAt: '2026-06-04T06:00:00.000Z',
  },
  // —— 意甲 ×4 ——
  {
    slug: 'inter-vs-ac-milan-2026-06-04',
    kickoffAt: '2026-06-04T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '圣西罗球场',
    round: '第37轮',
    home: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    away: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    direction: '国际米兰 -0.5',
    confidence: 'high',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 58,
    modelWinRate: 71,
    isHot: true,
    isFocus: true,
    pickType: 'home',
    homeRank: 1,
    awayRank: 4,
    h2hHome: 3,
    h2hDraw: 1,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.6,
    asianOpen: '国米 -0.5',
    asianCurrent: '国米 -0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-04T05:00:00.000Z',
  },
  {
    slug: 'juventus-vs-napoli-2026-06-05',
    kickoffAt: '2026-06-05T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '安联球场（都灵）',
    round: '第37轮',
    home: { slug: 'juventus', nameZh: '尤文图斯', abbr: 'JUV' },
    away: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.25',
    lineCurrent: '2.5',
    ouTrend: 'up',
    over25Prob: 65,
    modelWinRate: 65,
    isHot: true,
    pickType: 'over',
    homeRank: 3,
    awayRank: 2,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.4,
    asianOpen: '尤文 0',
    asianCurrent: '尤文 -0.25',
    asianTrend: 'up',
    publishedAt: '2026-06-05T06:00:00.000Z',
  },
  {
    slug: 'inter-vs-juventus-2026-06-05',
    kickoffAt: '2026-06-05T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '圣西罗球场',
    round: '第37轮',
    home: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    away: { slug: 'juventus', nameZh: '尤文图斯', abbr: 'JUV' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.25',
    lineCurrent: '2.5',
    ouTrend: 'up',
    over25Prob: 68,
    modelWinRate: 70,
    pickType: 'over',
    homeRank: 1,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.4,
    asianOpen: '国米 -0.25',
    asianCurrent: '国米 -0.5',
    asianTrend: 'up',
    publishedAt: '2026-06-05T05:00:00.000Z',
  },
  {
    slug: 'roma-vs-lazio-2026-06-06',
    kickoffAt: '2026-06-06T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '奥林匹克球场',
    round: '第37轮',
    home: { slug: 'roma', nameZh: '罗马', abbr: 'ROM' },
    away: { slug: 'lazio', nameZh: '拉齐奥', abbr: 'LAZ' },
    direction: '罗马 0',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 52,
    modelWinRate: 60,
    pickType: 'home',
    homeRank: 6,
    awayRank: 7,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 40,
    avgGoals: 2.2,
    asianOpen: '罗马 -0.25',
    asianCurrent: '罗马 0',
    asianTrend: 'down',
    publishedAt: '2026-06-06T06:00:00.000Z',
  },
];

export const batchPreMatchAnalyses: Record<string, PreMatchAnalysisDetail> = Object.fromEntries(
  BATCH_MATCH_SEEDS.map((seed) => [seed.slug, buildBatchAnalysis(seed)])
);

export const batchPreMatchAnalysisSlugs = BATCH_MATCH_SEEDS.map((s) => s.slug);

/** 批量模板 → 统一输入格式（供 analysis-registry 合并） */
export function batchSeedToDailyInput(seed: BatchMatchSeed): DailyAnalysisInput {
  return {
    slug: seed.slug,
    home: seed.home,
    away: seed.away,
    league: { slug: seed.leagueSlug, nameZh: seed.leagueName },
    kickoffAt: seed.kickoffAt,
    kickoffTimeDisplay: seed.kickoffTimeDisplay,
    direction: seed.direction,
    options: {
      confidence: seed.confidence,
      isHot: seed.isHot,
      isFocus: seed.isFocus,
      modelWinRate: seed.modelWinRate,
      venueZh: seed.venueZh,
      round: seed.round,
      pickType: seed.pickType,
      lineOpen: seed.lineOpen,
      lineCurrent: seed.lineCurrent,
      ouTrend: seed.ouTrend,
      over25Prob: seed.over25Prob,
      publishedAt: seed.publishedAt,
      showOnHomepage: Boolean(seed.isHot || seed.isFocus),
      featuredInLatest: Boolean(seed.isFocus),
    },
  };
}

export function getBatchDailyInputs(): DailyAnalysisInput[] {
  return BATCH_MATCH_SEEDS.map(batchSeedToDailyInput);
}
