import type { FormResult, PreMatchAnalysisDetail } from '@/types/analysis';

type Confidence = PreMatchAnalysisDetail['recommendation']['confidence'];

interface BatchMatchSeed {
  slug: string;
  kickoffAt: string;
  kickoffTimeDisplay: string;
  leagueSlug: string;
  leagueName: string;
  venueZh: string;
  round: string;
  home: { slug: string; nameZh: string; abbr: string };
  away: { slug: string; nameZh: string; abbr: string };
  direction: string;
  confidence: Confidence;
  lineOpen: string;
  lineCurrent: string;
  ouTrend: 'up' | 'down' | 'stable';
  over25Prob: number;
  modelWinRate: number;
  isHot?: boolean;
  isFocus?: boolean;
  pickType: 'over' | 'home' | 'away' | 'under';
  homeRank: number;
  awayRank: number;
  h2hHome: number;
  h2hDraw: number;
  h2hAway: number;
  over25Rate: number;
  avgGoals: number;
  asianOpen: string;
  asianCurrent: string;
  asianTrend: 'up' | 'down' | 'stable';
  publishedAt: string;
}

const FORM_CYCLE: FormResult[] = ['W', 'D', 'L'];

function hashSlug(slug: string): number {
  let h = 0;
  for (let i = 0; i < slug.length; i += 1) h = (h * 31 + slug.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function makeFormSequence(seed: number): FormResult[] {
  return Array.from({ length: 5 }, (_, i) => FORM_CYCLE[(seed + i * 2) % 3]);
}

function makeLast5(form: FormResult[]) {
  const w = form.filter((r) => r === 'W').length;
  const d = form.filter((r) => r === 'D').length;
  const l = form.filter((r) => r === 'L').length;
  return {
    w,
    d,
    l,
    gf: 7 + w * 2 + d,
    ga: 5 + l * 2 + Math.floor(d / 2),
  };
}

function trendFromForm(form: FormResult[], side: 'home' | 'away'): string {
  const w = form.filter((r) => r === 'W').length;
  const l = form.filter((r) => r === 'L').length;
  const sideZh = side === 'home' ? '主场' : '客场';
  if (w >= 4) return `${sideZh}4胜走势·进攻火热·需防连胜后回调`;
  if (w >= 3 && l <= 1) return `${sideZh}3胜1负·状态回升·终结效率稳定`;
  if (l >= 3) return `${sideZh}连场失球·防线松动·反击隐患大`;
  return `${sideZh}起伏明显·中场控制力一般·定位球占比高`;
}

const RELATED_POOL: Array<{ slug: string; title: string; league: string; kickoff: string }> = [
  { slug: 'man-united-vs-liverpool-2026-05-25', title: '曼联 對 利物浦 赛前分析', league: '英超', kickoff: '05-26 03:00' },
  { slug: 'arsenal-vs-man-city-2026-05-26', title: '阿森纳 對 曼城 赛前分析', league: '英超', kickoff: '05-27 03:00' },
  { slug: 'real-madrid-vs-barcelona-2026-05-27', title: '皇家马德里 對 巴塞罗那 赛前分析', league: '西甲', kickoff: '05-27 04:00' },
  { slug: 'bayern-vs-dortmund-2026-05-27', title: '拜仁慕尼黑 對 多特蒙德 赛前分析', league: '德甲', kickoff: '05-27 02:30' },
];

function pickRelated(slug: string): PreMatchAnalysisDetail['relatedArticles'] {
  const pool = RELATED_POOL.filter((r) => r.slug !== slug);
  return pool.slice(0, 2).map((r) => ({
    slug: r.slug,
    title: r.title,
    league: r.league,
    kickoff: r.kickoff,
  }));
}

function buildBatchAnalysis(seed: BatchMatchSeed): PreMatchAnalysisDetail {
  const h = hashSlug(seed.slug);
  const homeForm = makeFormSequence(h);
  const awayForm = makeFormSequence(h + 7);
  const homeLast5 = makeLast5(homeForm);
  const awayLast5 = makeLast5(awayForm);
  const homeGpg = Math.round((homeLast5.gf / 5) * 10) / 10;
  const awayGpg = Math.round((awayLast5.gf / 5) * 10) / 10;
  const homeCpg = Math.round((homeLast5.ga / 5) * 10) / 10;
  const awayCpg = Math.round((awayLast5.ga / 5) * 10) / 10;
  const homePoints = 38 + (5 - seed.homeRank) * 4 + homeLast5.w * 3;
  const awayPoints = 38 + (5 - seed.awayRank) * 4 + awayLast5.w * 3;

  const ouSummary =
    seed.ouTrend === 'up'
      ? `大小球由 ${seed.lineOpen} 升至 ${seed.lineCurrent}，大球水位持续走低，机构用升盘降水示好总进球；近5次交锋大2.5率 ${seed.over25Rate}%，模型概率 ${seed.over25Prob}%。临场若维持 ${seed.lineCurrent} 大球低水可跟，回落至 ${seed.lineOpen} 且大球升水则观望。`
      : seed.ouTrend === 'down'
        ? `大小球由 ${seed.lineOpen} 降至 ${seed.lineCurrent}，小球水位受压，市场担忧闷战或低节奏；交锋场均 ${seed.avgGoals} 球，仍须防「降盘诱小」后反弹。`
        : `大小球维持 ${seed.lineCurrent}，大球水位小幅震荡；交锋场均 ${seed.avgGoals} 球，大2.5率 ${seed.over25Rate}%，盘口未明显倾向，建议等临场水位再定。`;

  const oddsSummary = `${seed.leagueName}焦点战：亚盘初盘 ${seed.asianOpen}，后市 ${seed.asianCurrent}，资金对${seed.pickType === 'away' ? '客队' : seed.pickType === 'home' ? '主队' : '大球'}方向有持续承接。欧指与亚盘同向调整，角球盘略有抬升，侧面反映边路对攻频率不低。`;

  const recSummary =
    seed.pickType === 'over'
      ? `${seed.home.nameZh} vs ${seed.away.nameZh} 节奏偏快，大小升盘配低水，首选 ${seed.direction}；比分参考 2-1、2-2。完整临场方向开赛前会在 TG 更新。`
      : `${seed.leagueName}战意充足，盘口支持 ${seed.direction}，浅盘小胜格局可期。完整临场方向（水位、阵容）开赛前会在 TG 更新。`;

  return {
    slug: seed.slug,
    kickoffAt: seed.kickoffAt,
    kickoffTimeDisplay: seed.kickoffTimeDisplay,
    league: { slug: seed.leagueSlug, nameZh: seed.leagueName },
    status: 'scheduled',
    statusLabel: '未开赛',
    venueZh: seed.venueZh,
    round: seed.round,
    homeTeam: seed.home,
    awayTeam: seed.away,
    homeStatus: {
      teamName: seed.home.nameZh,
      side: 'home',
      leagueRank: seed.homeRank,
      points: homePoints,
      formSequence: homeForm,
      last5: homeLast5,
      goalsPerGame: homeGpg,
      concededPerGame: homeCpg,
      cleanSheets: Math.min(3, homeLast5.w),
      trendLabel: trendFromForm(homeForm, 'home'),
    },
    awayStatus: {
      teamName: seed.away.nameZh,
      side: 'away',
      leagueRank: seed.awayRank,
      points: awayPoints,
      formSequence: awayForm,
      last5: awayLast5,
      goalsPerGame: awayGpg,
      concededPerGame: awayCpg,
      cleanSheets: Math.min(3, awayLast5.w),
      trendLabel: trendFromForm(awayForm, 'away'),
    },
    headToHead: {
      summary: `近5次交锋 ${seed.home.nameZh}${seed.h2hHome}胜${seed.h2hDraw}和${seed.h2hAway}负，场均 ${seed.avgGoals} 球，大2.5率 ${seed.over25Rate}%。${seed.away.nameZh}客场进球稳定，${seed.home.nameZh}主场需改善开场阶段防守。`,
      homeWins: seed.h2hHome,
      draws: seed.h2hDraw,
      awayWins: seed.h2hAway,
      avgTotalGoals: seed.avgGoals,
      over25Rate: seed.over25Rate,
      matches: [
        { date: '2025-11', score: '2-1', competition: seed.leagueName, venue: 'home' },
        { date: '2025-04', score: '1-1', competition: seed.leagueName, venue: 'away' },
        { date: '2024-12', score: '0-2', competition: seed.leagueName, venue: 'away' },
        { date: '2024-03', score: '3-2', competition: seed.leagueName, venue: 'home' },
        { date: '2023-10', score: '1-0', competition: seed.leagueName, venue: 'home' },
      ],
    },
    oddsAnalysis: {
      summary: oddsSummary,
      rows: [
        { market: '亚盘', open: seed.asianOpen, current: seed.asianCurrent, trend: seed.asianTrend, move: seed.asianTrend === 'up' ? '主↑' : seed.asianTrend === 'down' ? '客↓' : '—' },
        { market: '1X2', open: '2.80 / 3.40 / 2.45', current: '2.65 / 3.55 / 2.55', trend: 'stable', move: '微调' },
        { market: '大小', open: `${seed.lineOpen} 大`, current: `${seed.lineCurrent} 大`, trend: seed.ouTrend, move: seed.ouTrend === 'up' ? '+升盘' : '—' },
      ],
    },
    overUnderAnalysis: {
      summary: ouSummary,
      lineOpen: seed.lineOpen,
      lineCurrent: seed.lineCurrent,
      trend: seed.ouTrend,
      overWaterOpen: '0.96',
      overWaterCurrent: seed.ouTrend === 'up' ? '0.88' : '0.94',
      underWaterCurrent: seed.ouTrend === 'up' ? '1.02' : '0.92',
      over25Probability: seed.over25Prob,
      waterTimeline: [
        { time: '48h', handicap: '0', totalLine: seed.lineOpen, overWater: '0.96', underWater: '0.94', tag: '初盘' },
        { time: '24h', handicap: '0', totalLine: seed.lineOpen, overWater: '0.93', underWater: '0.97' },
        { time: '6h', handicap: '0', totalLine: seed.lineCurrent, overWater: '0.90', underWater: '1.00' },
        { time: '临场', handicap: '0', totalLine: seed.lineCurrent, overWater: '0.88', underWater: '1.02', tag: seed.ouTrend === 'up' ? '大球热' : '观望' },
      ],
    },
    accessLabel: '免费公开',
    isHot: seed.isHot ?? false,
    isFocus: seed.isFocus ?? false,
    modelWinRate: seed.modelWinRate,
    recommendation: {
      direction: seed.direction,
      confidence: seed.confidence,
      scorePick: seed.pickType === 'over' ? '2-1 · 2-2 · 1-2' : '1-0 · 2-1 · 0-1',
      edge: `+${(2.5 + (h % 20) / 10).toFixed(1)}% EV`,
      summary: recSummary,
    },
    aiInsight: {
      pace: `${seed.home.nameZh}主场倾向${seed.pickType === 'over' ? '高位逼抢、边路提速' : '稳守反击'}；${seed.away.nameZh}客场${awayGpg >= 2 ? '推进节奏快' : '以控球消耗为主'}。预计开场 15–25 分钟节奏${seed.pickType === 'over' ? '偏快，不宜预期闷战' : '谨慎，下半场才拉开空间'}。`,
      attackDefense: `进攻：${seed.home.nameZh}近5场 ${homeLast5.gf} 入球，场均 ${homeGpg} 球，${seed.home.nameZh === '拜仁慕尼黑' || seed.home.nameZh === '曼城' ? '禁区压制力顶级' : '主场创造机会稳定'}；${seed.away.nameZh}近5场 ${awayLast5.gf} 入球，场均 ${awayGpg} 球，${awayGpg >= 2.2 ? '锋线转化率维持高位' : '终结效率一般' }。防守：${seed.home.nameZh}近5场 ${homeLast5.ga} 失球，${homeCpg >= 1.5 ? '高位线身后空档连场被利用' : '协防尚可但定位球二点偏弱'}；${seed.away.nameZh}客场 ${awayLast5.ga} 失球，${awayCpg >= 1.6 ? '中卫回追速度是隐患' : '零封率偏低需留意'}。`,
      ev: `模型 ${seed.direction} 胜率约 ${seed.modelWinRate}%，对比市场隐含概率估算 ${(2.5 + (h % 20) / 10).toFixed(1)}% EV；亚盘与大小盘信号${seed.pickType === 'over' ? '同向看好总进球' : '共振支持赛果盘'}。`,
      risk: `${seed.confidence === 'high' ? '中等' : '偏高'}风险：战意或轮换影响节奏；临场水位若逆向需减仓。完整临场方向开赛前会在 TG 更新。`,
    },
    riskWarning: {
      level: seed.confidence === 'high' ? 'medium' : 'medium',
      items: [
        `${seed.leagueName}关键战，战术突变或早段红牌会彻底改变盘口逻辑`,
        `${seed.home.nameZh}若临场确认主力缺阵，需重估${seed.pickType === 'over' ? '大球' : '让球'}价值`,
        `大小球临场若由 ${seed.lineCurrent} 回落 ${seed.lineOpen} 且大球升水，不宜硬跟`,
        `走地须另作判断，勿用赛前盘直接套用`,
        '完整临场方向（最终大小球线、亚盘跟进）开赛前会在 TG 更新，请以频道推送为准',
      ],
    },
    relatedArticles: pickRelated(seed.slug),
    publishedAt: seed.publishedAt,
  };
}

const BATCH_MATCH_SEEDS: BatchMatchSeed[] = [
  // —— 英超 ×4 ——
  {
    slug: 'liverpool-vs-man-city-2026-05-28',
    kickoffAt: '2026-05-28T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '安菲尔德',
    round: '第38轮',
    home: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 74,
    modelWinRate: 74,
    isHot: true,
    pickType: 'over',
    homeRank: 2,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '平手',
    asianCurrent: '利物浦 -0.25',
    asianTrend: 'up',
    publishedAt: '2026-05-28T06:00:00.000Z',
  },
  {
    slug: 'chelsea-vs-arsenal-2026-05-28',
    kickoffAt: '2026-05-28T16:30:00.000Z',
    kickoffTimeDisplay: '00:30',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '斯坦福桥',
    round: '第38轮',
    home: { slug: 'chelsea', nameZh: '切尔西', abbr: 'CHE' },
    away: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    direction: '阿森纳 -0.25',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 55,
    modelWinRate: 62,
    isHot: true,
    pickType: 'away',
    homeRank: 5,
    awayRank: 1,
    h2hHome: 1,
    h2hDraw: 2,
    h2hAway: 2,
    over25Rate: 60,
    avgGoals: 2.6,
    asianOpen: '切尔西 +0.25',
    asianCurrent: '切尔西 +0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-28T05:00:00.000Z',
  },
  {
    slug: 'man-united-vs-man-city-2026-05-29',
    kickoffAt: '2026-05-29T11:30:00.000Z',
    kickoffTimeDisplay: '19:30',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '老特拉福德',
    round: '第38轮',
    home: { slug: 'man-united', nameZh: '曼联', abbr: 'MUN' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '曼城 -0.75',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '2.75',
    ouTrend: 'stable',
    over25Prob: 68,
    modelWinRate: 70,
    isFocus: true,
    pickType: 'away',
    homeRank: 6,
    awayRank: 3,
    h2hHome: 0,
    h2hDraw: 1,
    h2hAway: 4,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '曼联 +0.75',
    asianCurrent: '曼联 +0.75',
    asianTrend: 'down',
    publishedAt: '2026-05-29T04:00:00.000Z',
  },
  {
    slug: 'tottenham-vs-newcastle-2026-05-29',
    kickoffAt: '2026-05-29T14:00:00.000Z',
    kickoffTimeDisplay: '22:00',
    leagueSlug: 'epl',
    leagueName: '英超',
    venueZh: '托特纳姆热刺球场',
    round: '第38轮',
    home: { slug: 'tottenham', nameZh: '热刺', abbr: 'TOT' },
    away: { slug: 'newcastle', nameZh: '纽卡斯尔', abbr: 'NEW' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 66,
    modelWinRate: 66,
    pickType: 'over',
    homeRank: 7,
    awayRank: 8,
    h2hHome: 3,
    h2hDraw: 0,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '热刺 -0.25',
    asianCurrent: '热刺 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-29T05:00:00.000Z',
  },
  // —— 欧冠 ×4 ——
  {
    slug: 'real-madrid-vs-man-city-2026-05-29',
    kickoffAt: '2026-05-29T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '伯纳乌球场',
    round: '半决赛次回合',
    home: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    away: { slug: 'man-city', nameZh: '曼城', abbr: 'MCI' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 76,
    modelWinRate: 76,
    isHot: true,
    isFocus: true,
    pickType: 'over',
    homeRank: 1,
    awayRank: 2,
    h2hHome: 3,
    h2hDraw: 0,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.2,
    asianOpen: '皇马 -0.25',
    asianCurrent: '皇马 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-29T06:00:00.000Z',
  },
  {
    slug: 'barcelona-vs-bayern-2026-05-30',
    kickoffAt: '2026-05-30T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '诺坎普球场',
    round: '半决赛次回合',
    home: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 78,
    modelWinRate: 78,
    isHot: true,
    pickType: 'over',
    homeRank: 2,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 100,
    avgGoals: 3.6,
    asianOpen: '巴萨 -0.25',
    asianCurrent: '平手',
    asianTrend: 'down',
    publishedAt: '2026-05-30T06:00:00.000Z',
  },
  {
    slug: 'liverpool-vs-real-madrid-2026-05-30',
    kickoffAt: '2026-05-30T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '安菲尔德',
    round: '8强次回合',
    home: { slug: 'liverpool', nameZh: '利物浦', abbr: 'LIV' },
    away: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    direction: '利物浦 -0.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '2.75',
    ouTrend: 'stable',
    over25Prob: 70,
    modelWinRate: 65,
    pickType: 'home',
    homeRank: 4,
    awayRank: 5,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '利物浦 -0.25',
    asianCurrent: '利物浦 -0.5',
    asianTrend: 'up',
    publishedAt: '2026-05-30T05:00:00.000Z',
  },
  {
    slug: 'arsenal-vs-bayern-2026-05-31',
    kickoffAt: '2026-05-31T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'ucl',
    leagueName: '欧冠',
    venueZh: '酋长球场',
    round: '8强次回合',
    home: { slug: 'arsenal', nameZh: '阿森纳', abbr: 'ARS' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.5',
    lineCurrent: '2.75',
    ouTrend: 'up',
    over25Prob: 72,
    modelWinRate: 72,
    isHot: true,
    pickType: 'over',
    homeRank: 6,
    awayRank: 3,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.2,
    asianOpen: '阿森纳 +0.25',
    asianCurrent: '阿森纳 +0.25',
    asianTrend: 'stable',
    publishedAt: '2026-05-31T06:00:00.000Z',
  },
  // —— 西甲 ×4 ——
  {
    slug: 'atletico-vs-barcelona-2026-05-31',
    kickoffAt: '2026-05-31T16:15:00.000Z',
    kickoffTimeDisplay: '00:15',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '万达大都会球场',
    round: '第37轮',
    home: { slug: 'atletico', nameZh: '马德里竞技', abbr: 'ATM' },
    away: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    direction: '小 2.5',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.25',
    ouTrend: 'down',
    over25Prob: 42,
    modelWinRate: 58,
    pickType: 'under',
    homeRank: 4,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 40,
    avgGoals: 2.2,
    asianOpen: '马竞 0',
    asianCurrent: '马竞 0',
    asianTrend: 'stable',
    publishedAt: '2026-05-31T05:00:00.000Z',
  },
  {
    slug: 'real-madrid-vs-sevilla-2026-06-01',
    kickoffAt: '2026-06-01T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '伯纳乌球场',
    round: '第37轮',
    home: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    away: { slug: 'sevilla', nameZh: '塞维利亚', abbr: 'SEV' },
    direction: '皇马 -1',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.0',
    ouTrend: 'stable',
    over25Prob: 68,
    modelWinRate: 73,
    isHot: true,
    pickType: 'home',
    homeRank: 2,
    awayRank: 9,
    h2hHome: 4,
    h2hDraw: 1,
    h2hAway: 0,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '皇马 -1',
    asianCurrent: '皇马 -1',
    asianTrend: 'stable',
    publishedAt: '2026-06-01T06:00:00.000Z',
  },
  {
    slug: 'barcelona-vs-valencia-2026-06-01',
    kickoffAt: '2026-06-01T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '诺坎普球场',
    round: '第37轮',
    home: { slug: 'barcelona', nameZh: '巴塞罗那', abbr: 'BAR' },
    away: { slug: 'valencia', nameZh: '瓦伦西亚', abbr: 'VAL' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 76,
    modelWinRate: 76,
    pickType: 'over',
    homeRank: 3,
    awayRank: 12,
    h2hHome: 4,
    h2hDraw: 1,
    h2hAway: 0,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '巴萨 -1.25',
    asianCurrent: '巴萨 -1.5',
    asianTrend: 'up',
    publishedAt: '2026-06-01T05:00:00.000Z',
  },
  {
    slug: 'villarreal-vs-real-madrid-2026-06-02',
    kickoffAt: '2026-06-02T19:00:00.000Z',
    kickoffTimeDisplay: '03:00',
    leagueSlug: 'la-liga',
    leagueName: '西甲',
    venueZh: '陶瓷球场',
    round: '第37轮',
    home: { slug: 'villarreal', nameZh: '比利亚雷亚尔', abbr: 'VIL' },
    away: { slug: 'real-madrid', nameZh: '皇家马德里', abbr: 'RMA' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 70,
    modelWinRate: 68,
    pickType: 'over',
    homeRank: 5,
    awayRank: 2,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.0,
    asianOpen: '黄潜 +0.5',
    asianCurrent: '黄潜 +0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-02T06:00:00.000Z',
  },
  // —— 德甲 ×4 ——
  {
    slug: 'leverkusen-vs-bayern-2026-06-02',
    kickoffAt: '2026-06-02T16:30:00.000Z',
    kickoffTimeDisplay: '00:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '拜耳球场',
    round: '第33轮',
    home: { slug: 'leverkusen', nameZh: '勒沃库森', abbr: 'B04' },
    away: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    direction: '拜仁 -0.5',
    confidence: 'high',
    lineOpen: '3.25',
    lineCurrent: '3.5',
    ouTrend: 'up',
    over25Prob: 75,
    modelWinRate: 72,
    isHot: true,
    pickType: 'away',
    homeRank: 2,
    awayRank: 1,
    h2hHome: 1,
    h2hDraw: 1,
    h2hAway: 3,
    over25Rate: 80,
    avgGoals: 3.6,
    asianOpen: '勒沃库森 +0.5',
    asianCurrent: '勒沃库森 +0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-02T05:00:00.000Z',
  },
  {
    slug: 'dortmund-vs-rb-leipzig-2026-06-03',
    kickoffAt: '2026-06-03T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '威斯特法伦球场',
    round: '第33轮',
    home: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    away: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '3.0',
    lineCurrent: '3.25',
    ouTrend: 'up',
    over25Prob: 77,
    modelWinRate: 77,
    isHot: true,
    pickType: 'over',
    homeRank: 4,
    awayRank: 5,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 80,
    avgGoals: 3.4,
    asianOpen: '多特 -0.25',
    asianCurrent: '多特 -0.25',
    asianTrend: 'stable',
    publishedAt: '2026-06-03T06:00:00.000Z',
  },
  {
    slug: 'bayern-vs-rb-leipzig-2026-06-03',
    kickoffAt: '2026-06-03T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '安联球场',
    round: '第33轮',
    home: { slug: 'bayern', nameZh: '拜仁慕尼黑', abbr: 'BAY' },
    away: { slug: 'rb-leipzig', nameZh: 'RB莱比锡', abbr: 'RBL' },
    direction: '拜仁 -0.75',
    confidence: 'high',
    lineOpen: '3.5',
    lineCurrent: '3.5',
    ouTrend: 'stable',
    over25Prob: 72,
    modelWinRate: 74,
    isFocus: true,
    pickType: 'home',
    homeRank: 1,
    awayRank: 5,
    h2hHome: 4,
    h2hDraw: 0,
    h2hAway: 1,
    over25Rate: 80,
    avgGoals: 3.8,
    asianOpen: '拜仁 -0.75',
    asianCurrent: '拜仁 -0.75',
    asianTrend: 'stable',
    publishedAt: '2026-06-03T05:00:00.000Z',
  },
  {
    slug: 'frankfurt-vs-dortmund-2026-06-04',
    kickoffAt: '2026-06-04T18:30:00.000Z',
    kickoffTimeDisplay: '02:30',
    leagueSlug: 'bundesliga',
    leagueName: '德甲',
    venueZh: '德意志银行公园',
    round: '第33轮',
    home: { slug: 'frankfurt', nameZh: '法兰克福', abbr: 'SGE' },
    away: { slug: 'dortmund', nameZh: '多特蒙德', abbr: 'BVB' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.75',
    lineCurrent: '3.0',
    ouTrend: 'up',
    over25Prob: 69,
    modelWinRate: 67,
    pickType: 'over',
    homeRank: 6,
    awayRank: 4,
    h2hHome: 2,
    h2hDraw: 0,
    h2hAway: 3,
    over25Rate: 60,
    avgGoals: 2.8,
    asianOpen: '法兰克福 +0.25',
    asianCurrent: '法兰克福 0',
    asianTrend: 'up',
    publishedAt: '2026-06-04T06:00:00.000Z',
  },
  // —— 意甲 ×4 ——
  {
    slug: 'inter-vs-ac-milan-2026-06-04',
    kickoffAt: '2026-06-04T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '圣西罗球场',
    round: '第37轮',
    home: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    away: { slug: 'ac-milan', nameZh: 'AC米兰', abbr: 'MIL' },
    direction: '国际米兰 -0.5',
    confidence: 'high',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 58,
    modelWinRate: 71,
    isHot: true,
    isFocus: true,
    pickType: 'home',
    homeRank: 1,
    awayRank: 4,
    h2hHome: 3,
    h2hDraw: 1,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.6,
    asianOpen: '国米 -0.5',
    asianCurrent: '国米 -0.5',
    asianTrend: 'stable',
    publishedAt: '2026-06-04T05:00:00.000Z',
  },
  {
    slug: 'juventus-vs-napoli-2026-06-05',
    kickoffAt: '2026-06-05T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '安联球场（都灵）',
    round: '第37轮',
    home: { slug: 'juventus', nameZh: '尤文图斯', abbr: 'JUV' },
    away: { slug: 'napoli', nameZh: '那不勒斯', abbr: 'NAP' },
    direction: '大 2.5',
    confidence: 'medium',
    lineOpen: '2.25',
    lineCurrent: '2.5',
    ouTrend: 'up',
    over25Prob: 65,
    modelWinRate: 65,
    isHot: true,
    pickType: 'over',
    homeRank: 3,
    awayRank: 2,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.4,
    asianOpen: '尤文 0',
    asianCurrent: '尤文 -0.25',
    asianTrend: 'up',
    publishedAt: '2026-06-05T06:00:00.000Z',
  },
  {
    slug: 'inter-vs-juventus-2026-06-05',
    kickoffAt: '2026-06-05T16:00:00.000Z',
    kickoffTimeDisplay: '00:00',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '圣西罗球场',
    round: '第37轮',
    home: { slug: 'inter', nameZh: '国际米兰', abbr: 'INT' },
    away: { slug: 'juventus', nameZh: '尤文图斯', abbr: 'JUV' },
    direction: '大 2.5',
    confidence: 'high',
    lineOpen: '2.25',
    lineCurrent: '2.5',
    ouTrend: 'up',
    over25Prob: 68,
    modelWinRate: 70,
    pickType: 'over',
    homeRank: 1,
    awayRank: 3,
    h2hHome: 2,
    h2hDraw: 2,
    h2hAway: 1,
    over25Rate: 60,
    avgGoals: 2.4,
    asianOpen: '国米 -0.25',
    asianCurrent: '国米 -0.5',
    asianTrend: 'up',
    publishedAt: '2026-06-05T05:00:00.000Z',
  },
  {
    slug: 'roma-vs-lazio-2026-06-06',
    kickoffAt: '2026-06-06T18:45:00.000Z',
    kickoffTimeDisplay: '02:45',
    leagueSlug: 'serie-a',
    leagueName: '意甲',
    venueZh: '奥林匹克球场',
    round: '第37轮',
    home: { slug: 'roma', nameZh: '罗马', abbr: 'ROM' },
    away: { slug: 'lazio', nameZh: '拉齐奥', abbr: 'LAZ' },
    direction: '罗马 0',
    confidence: 'medium',
    lineOpen: '2.5',
    lineCurrent: '2.5',
    ouTrend: 'stable',
    over25Prob: 52,
    modelWinRate: 60,
    pickType: 'home',
    homeRank: 6,
    awayRank: 7,
    h2hHome: 2,
    h2hDraw: 1,
    h2hAway: 2,
    over25Rate: 40,
    avgGoals: 2.2,
    asianOpen: '罗马 -0.25',
    asianCurrent: '罗马 0',
    asianTrend: 'down',
    publishedAt: '2026-06-06T06:00:00.000Z',
  },
];

export const batchPreMatchAnalyses: Record<string, PreMatchAnalysisDetail> = Object.fromEntries(
  BATCH_MATCH_SEEDS.map((seed) => [seed.slug, buildBatchAnalysis(seed)])
);

export const batchPreMatchAnalysisSlugs = BATCH_MATCH_SEEDS.map((s) => s.slug);
